// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { configDotenv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js stores secrets in .env.local; dotenv/config only reads .env by default
configDotenv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) URL for migrations — PgBouncer rejects DDL statements
    url: process.env["DIRECT_URL"],
  },
});
