import { NextResponse } from 'next/server';
import { isRecord, updateProjectSubresource } from '@/lib/projects/project-subresource';

export const dynamic = 'force-dynamic';

type RouteContext = { params: Promise<{ id: string }> };

function optionalString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

/** POST /api/projects/[id]/tasks — create an ad-hoc project task. */
export async function POST(request: Request, context: RouteContext) {
  const { id } = await context.params;

  let body: Record<string, unknown> = {};
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const title = optionalString(body.title);
  if (!title) {
    return NextResponse.json({ error: 'Task title is required.' }, { status: 400 });
  }

  const taskId = `task-${crypto.randomUUID()}`;
  const taskFields = {
    id: taskId,
    title,
    description: optionalString(body.description),
    assignedTo: optionalString(body.assignedTo),
    assigneeName: optionalString(body.assigneeName) ?? optionalString(body.assignedTo),
    assignedToUid: optionalString(body.assignedToUid),
    assigneeUid: optionalString(body.assigneeUid) ?? optionalString(body.assignedToUid),
    dueDate: optionalString(body.dueDate) ?? new Date().toISOString(),
    status: optionalString(body.status) ?? 'pending',
    isAutoGenerated: body.isAutoGenerated === true,
    linkedContingencyId: optionalString(body.linkedContingencyId),
    createdAt: new Date().toISOString(),
  };

  const result = await updateProjectSubresource(request, id, (current) => {
    const tasks = Array.isArray(current.tasks) ? current.tasks : [];
    return { tasks: [...tasks, taskFields] };
  });

  if (!result.ok) return result.response;

  const tasks = Array.isArray(result.project.tasks) ? result.project.tasks : [];
  const task = tasks.find((item) => isRecord(item) && item.id === taskId) ?? taskFields;

  return NextResponse.json({ success: true, task });
}
