export interface Todo {
  id: string;
  type: 'question' | 'upload' | 'delegate';
  label: string;
  description: string;
  completed: boolean;
  actionText: string;
  assignee?: string | null;
  allowedRoles?: string[];
}

export const DEFAULT_TODOS: Record<number, Todo[]> = {
  1: [
    {
      id: 't1_1',
      type: 'question',
      label: 'Neighborhood Confirmed',
      description: 'Have you identified and researched the target neighborhood for this project?',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't1_2',
      type: 'question',
      label: 'Property Condition Assessment',
      description: 'On a scale of 1–10, what condition is this property in? Note any structural, roof, foundation, or systems issues.',
      completed: false,
      actionText: 'Assess',
    },
    {
      id: 't1_3',
      type: 'question',
      label: 'Title Status',
      description: 'Is the title clear, or are there clouds, liens, or encumbrances that need resolution before closing?',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't1_4',
      type: 'question',
      label: 'Comparable Sales Reviewed',
      description: 'Have you pulled and reviewed comparable sales to validate your ARV assumption? Bad comps = bad ARV = bad everything.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't1_5',
      type: 'upload',
      label: 'Inspection Report',
      description: 'Upload the property inspection report. This is the foundation of your rehab budget.',
      completed: false,
      actionText: 'Upload Report',
    },
    {
      id: 't1_6',
      type: 'upload',
      label: 'Title Search / Title Report',
      description: 'Upload the title search results. Confirms ownership and reveals any liens or encumbrances.',
      completed: false,
      actionText: 'Upload Title',
    },
    {
      id: 't1_7',
      type: 'upload',
      label: 'Appraisal or BPO',
      description: 'Upload the appraisal or Broker Price Opinion to support your ARV estimate.',
      completed: false,
      actionText: 'Upload Appraisal',
    },
    {
      id: 't1_8',
      type: 'upload',
      label: 'Survey / Plat Map',
      description: 'Upload the property survey or plat map showing boundaries and easements.',
      completed: false,
      actionText: 'Upload Survey',
    },
    {
      id: 't1_9',
      type: 'delegate',
      label: 'Loan Officer',
      description: 'Do you need to find a loan officer for financing this acquisition?',
      completed: false,
      actionText: 'Find Loan Officer',
    },
    {
      id: 't1_10',
      type: 'delegate',
      label: 'Home Inspector',
      description: 'Do you need to find a licensed home inspector to evaluate the property?',
      completed: false,
      actionText: 'Find Inspector',
    },
    {
      id: 't1_11',
      type: 'delegate',
      label: 'Appraiser',
      description: 'Do you need to find an appraiser to confirm property value before closing?',
      completed: false,
      actionText: 'Find Appraiser',
    },
    {
      id: 't1_12',
      type: 'delegate',
      label: 'Insurance Agent',
      description: 'Do you need to get insurance quotes (hazard, liability, builder\'s risk) before closing?',
      completed: false,
      actionText: 'Find Agent',
    },
    {
      id: 't1_13',
      type: 'delegate',
      label: 'Offer Letter Generation',
      description: 'Draft and generate the official offer letter for the property using the role matrix.',
      completed: false,
      actionText: 'Generate Offer',
      allowedRoles: ['Real Estate Agent', 'Real Estate Attorney', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't1_14',
      type: 'delegate',
      label: 'Offer Response Tracking',
      description: 'Track counter-offers, acceptance status, and contingencies for the offer.',
      completed: false,
      actionText: 'Track Response',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't1_15',
      type: 'delegate',
      label: 'Investor Outreach',
      description: 'Reach out to the investor list to pitch the opportunity and collect pledges.',
      completed: false,
      actionText: 'Start Outreach',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't1_16',
      type: 'delegate',
      label: 'Deal Marketplace Post',
      description: 'Post the project to the Deal Marketplace to find external buyers or partners.',
      completed: false,
      actionText: 'Post to Marketplace',
      allowedRoles: ['Lead Investor', 'Admin', 'Platform Admin'],
    },
  ],
  2: [
    {
      id: 't2_1',
      type: 'question',
      label: 'Pre-Approval Secured',
      description: 'Have you secured pre-approval from your lender? Pre-approval before making offers demonstrates you\'re a serious buyer and lets you close quickly — a powerful negotiating tool.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't2_2',
      type: 'delegate',
      label: 'Hard Money / Private Lender',
      description: 'Don\'t rely on a single funding source. Build relationships with multiple hard money lenders and private investors to compare terms and have backup options.',
      completed: false,
      actionText: 'Find Lender',
    },
    {
      id: 't2_3',
      type: 'upload',
      label: 'Loan Commitment Letter',
      description: 'Upload the lender\'s commitment letter confirming loan approval, rate, LTV, and draw schedule terms.',
      completed: false,
      actionText: 'Upload Letter',
    },
    {
      id: 't2_4',
      type: 'question',
      label: 'Line-Item Budget Created',
      description: 'Have you built a line-item budget covering every cost? Include dumpster fees, portable toilets, utility bills, insurance premiums, and final cleaning — not just kitchens and baths.',
      completed: false,
      actionText: 'Review Budget',
    },
    {
      id: 't2_5',
      type: 'question',
      label: '15% Contingency Funded',
      description: 'Have you set aside 10-20% of your repair costs as a contingency fund? This covers hidden foundation cracks, rotted subfloors, and unexpected plumbing — not upgrades.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't2_6',
      type: 'question',
      label: 'Daily Burn Rate Calculated',
      description: 'Do you know your daily holding cost? Once the loan closes, every day has a dollar amount. If holding costs are $3,000/mo, your burn rate is $100/day. This creates urgency.',
      completed: false,
      actionText: 'View Burn Rate',
    },
    {
      id: 't2_7',
      type: 'upload',
      label: 'Purchase Agreement',
      description: 'Upload the executed purchase & sale agreement. This is your binding contract.',
      completed: false,
      actionText: 'Upload Contract',
    },
    {
      id: 't2_8',
      type: 'upload',
      label: 'Closing Disclosures',
      description: 'Upload the lender\'s closing disclosure (CD) and HUD-1 settlement statement.',
      completed: false,
      actionText: 'Upload CD',
    },
    {
      id: 't2_9',
      type: 'upload',
      label: 'Proof of Insurance',
      description: 'Upload your hazard insurance binder. Required before closing and draw disbursement.',
      completed: false,
      actionText: 'Upload Binder',
    },
    {
      id: 't2_10',
      type: 'question',
      label: 'EMD Delivered',
      description: 'Has the earnest money deposit been delivered to escrow and confirmed received?',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't2_11',
      type: 'question',
      label: 'Title Clear to Close',
      description: 'Has the title company confirmed clear title with no unresolved liens or encumbrances?',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't2_12',
      type: 'delegate',
      label: 'Real Estate Attorney',
      description: 'Do you need to find a real estate attorney to handle closing and title work?',
      completed: false,
      actionText: 'Find Attorney',
    },
  ],
  3: [
    {
      id: 't3_1',
      type: 'upload',
      label: 'Design Scope Document',
      description: 'Upload your renovation scope document with room-by-room design specifications. A detailed plan is non-negotiable — every dollar must map to a specific task that increases resale value.',
      completed: false,
      actionText: 'Upload Design Scope',
    },
    {
      id: 't3_2',
      type: 'question',
      label: '"Money Rooms" Budget Allocated',
      description: 'Have you allocated 50-60% of your rehab budget to kitchen and bathroom renovations? These are the rooms that sell houses. Skimping here and splurging elsewhere destroys ROI.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't3_3',
      type: 'question',
      label: 'Curb Appeal Scope Defined',
      description: 'Front door, exterior paint, landscaping, house numbers, clean porch — have you defined and budgeted your curb appeal upgrades? First impression costs little but dramatically increases buyer interest.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't3_4',
      type: 'question',
      label: 'Neutral Palette Confirmed',
      description: 'Are you using neutral colors (greys, beiges, off-whites) for walls and permanent fixtures? Bold colors narrow your buyer pool. Introduce trendy color only through staging items.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't3_5',
      type: 'delegate',
      label: 'General Contractor',
      description: 'Do you need to find a GC for the renovation work? Get at least 3 bids before selecting.',
      completed: false,
      actionText: 'Find GC',
    },
    {
      id: 't3_6',
      type: 'upload',
      label: 'Contractor Bid Comparison',
      description: 'Upload at least 3 contractor bids to compare pricing, timelines, and scope before selecting your GC. Never hire the first bid.',
      completed: false,
      actionText: 'Upload Bids',
    },
    {
      id: 't3_7',
      type: 'upload',
      label: 'Building Permits',
      description: 'Upload approved city/county permits for the renovation scope. Unpermitted work kills deals at resale.',
      completed: false,
      actionText: 'Upload Permits',
    },
    {
      id: 't3_8',
      type: 'upload',
      label: 'Scope of Work (SOW)',
      description: 'Upload the signed scope of work with your GC — line-item breakdown of all rehab tasks with dollar amounts and completion dates.',
      completed: false,
      actionText: 'Upload SOW',
    },
    {
      id: 't3_9',
      type: 'question',
      label: 'Over-Improvement Check',
      description: 'Is your total renovation spend under 30% of your ARV? If every home in the neighborhood has laminate countertops, installing high-end marble won\'t provide a return. Match the standard of the area.',
      completed: false,
      actionText: 'Review',
    },
    {
      id: 't3_10',
      type: 'question',
      label: 'Rehab Budget vs. Actual',
      description: 'Is actual spending tracking within 10% of your projected rehab budget? Review the cost ledger. Overruns compound with holding costs.',
      completed: false,
      actionText: 'Review',
    },
    {
      id: 't3_11',
      type: 'question',
      label: 'Timeline Check',
      description: 'Is the rehab on schedule? Every extra day increases holding costs (insurance, taxes, loan interest). Check your daily burn rate.',
      completed: false,
      actionText: 'Review',
    },
    {
      id: 't3_12',
      type: 'question',
      label: 'Holding Costs Current',
      description: 'Are all holding costs (utilities, insurance, taxes, loan payments) being tracked? These are the costs most REIs miss — and they\'re bleeding money every day.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't3_13',
      type: 'upload',
      label: 'Final Inspection Report',
      description: 'Upload the final city inspection or certificate of occupancy once rehab is complete.',
      completed: false,
      actionText: 'Upload Report',
    },
    {
      id: 't3_14',
      type: 'delegate',
      label: 'Property Manager',
      description: 'If holding as a rental, do you need to find a property manager before tenants move in?',
      completed: false,
      actionText: 'Find PM',
    },
    {
      id: 't3_15',
      type: 'delegate',
      label: 'Rehab Contractor Assignment',
      description: 'Assign a licensed general contractor or specialty subcontractors to execute the rehab work.',
      completed: false,
      actionText: 'Assign Contractor',
      allowedRoles: ['General Contractor', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't3_16',
      type: 'upload',
      label: 'Rehab Expense Receipt Upload',
      description: 'Upload project expense receipts and vendor invoices to keep the rehab ledger accurate and up-to-date.',
      completed: false,
      actionText: 'Upload Receipt',
      allowedRoles: ['General Contractor', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't3_17',
      type: 'delegate',
      label: 'Tenant Placement',
      description: 'For rental strategies, screen applicants, execute the lease agreement, and collect security deposit.',
      completed: false,
      actionText: 'Place Tenant',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't3_18',
      type: 'question',
      label: 'Periodic Value Update',
      description: 'Update the estimated current market value of the property based on local market comps or neighborhood changes.',
      completed: false,
      actionText: 'Update Value',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin', 'Analyst'],
    },
  ],
  4: [
    {
      id: 't4_1',
      type: 'delegate',
      label: 'Listing Agent',
      description: 'Do you need to find a listing agent to market and sell the property?',
      completed: false,
      actionText: 'Find Agent',
    },
    {
      id: 't4_2',
      type: 'upload',
      label: 'Professional Photos & Media',
      description: 'Upload professional listing photos and video walkthrough for MLS and marketing.',
      completed: false,
      actionText: 'Upload Media',
    },
    {
      id: 't4_3',
      type: 'question',
      label: 'Listing Price Set',
      description: 'Have you set the listing price based on updated comps and your target ROI? Compare against your original ARV.',
      completed: false,
      actionText: 'Confirm',
    },
    {
      id: 't4_4',
      type: 'question',
      label: 'Final P&L Reviewed',
      description: 'Have you reviewed the final Profit & Loss including all acquisition, rehab, holding, and selling costs?',
      completed: false,
      actionText: 'Review',
    },
    {
      id: 't4_5',
      type: 'upload',
      label: 'Settlement Statement (HUD-1)',
      description: 'Upload the final closing settlement statement from the sale.',
      completed: false,
      actionText: 'Upload HUD-1',
    },
    {
      id: 't4_6',
      type: 'question',
      label: 'Tax Documents Generated',
      description: 'Have your quarterly and/or yearly tax documents been generated from this project\'s earnings?',
      completed: false,
      actionText: 'Generate',
    },
    {
      id: 't4_7',
      type: 'delegate',
      label: 'Listing Agent Assignment',
      description: 'Assign a licensed listing agent to manage marketing, MLS syndication, and open houses.',
      completed: false,
      actionText: 'Assign Agent',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't4_8',
      type: 'upload',
      label: 'Marketing Cost Tracking',
      description: 'Upload receipts and invoices for marketing expenses, including staging, professional media, and listing fees.',
      completed: false,
      actionText: 'Upload Receipts',
      allowedRoles: ['Real Estate Agent', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't4_9',
      type: 'upload',
      label: 'Closing Document Collection',
      description: 'Collect and upload legal documents for closing, including title insurance commitment, escrow instructions, and deeds.',
      completed: false,
      actionText: 'Upload Documents',
      allowedRoles: ['Real Estate Attorney', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
    {
      id: 't4_10',
      type: 'question',
      label: 'End-of-Period Tax Document Generation',
      description: 'Confirm and finalize tax data aggregation for the realized sale period.',
      completed: false,
      actionText: 'Finalize Tax Data',
      allowedRoles: ['Accountant', 'Lead Investor', 'Admin', 'Platform Admin'],
    },
  ]
};
