import type { InboxThread } from '../../apps/web/lib/inbox/types';

/** Seed feed — mirrors PaperWorking unified notification center. */
export const INBOX_THREADS: InboxThread[] = [
  {
    id: 'thread-1',
    tab: 'opportunities',
    type: 'INVEST_INVITE',
    subject: 'Loan estimate ready for review',
    project: '88 Harbor Lane',
    from: 'Capital Partners Lending',
    fromRole: 'Lender',
    preview: 'Updated soft terms for the bridge facility — review before Friday.',
    body: 'Updated soft terms for the bridge facility on 88 Harbor Lane are ready for review.\n\nSoft quote: 9.25% interest-only · 18-month term · 70% LTC.\nPlease confirm by Friday so we can lock the rate sheet.',
    unread: true,
    receivedAt: '2026-08-19T14:22:00Z',
    deepLinkUrl: '/dashboard/projects',
    actionable: true,
  },
  {
    id: 'thread-2',
    tab: 'vendor',
    type: 'VENDOR_BID',
    subject: 'Vendor quote submitted — roof inspection',
    project: '1247 Elm Street',
    from: 'Summit Roofing Co.',
    fromRole: 'Vendor',
    preview: 'Quote #SR-441 attached. Site visit available next Tuesday.',
    body: 'Quote #SR-441 for roof inspection on 1247 Elm Street.\n\nProposed service date: next Tuesday.\nPayment terms: Net 15 upon completion.\nScope: full roof walk + moisture scan + written report.',
    unread: true,
    receivedAt: '2026-08-18T09:10:00Z',
    deepLinkUrl: '/dashboard/projects',
    actionable: true,
  },
  {
    id: 'thread-3',
    tab: 'system',
    type: 'SYSTEM',
    subject: 'Quarterly report exported',
    project: 'Portfolio',
    from: 'PaperWorking Reports',
    fromRole: 'System',
    preview: 'Your Q2 PDF is ready in Reports → Exports.',
    body: 'Your Q2 portfolio PDF package finished exporting.\n\nOpen Reports to download the Tax Intelligence package or re-run for another period.',
    unread: false,
    receivedAt: '2026-08-17T16:45:00Z',
    deepLinkUrl: '/dashboard/reports',
  },
  {
    id: 'thread-4',
    tab: 'tasks',
    type: 'DEADLINE_ALERT',
    subject: 'Task due: Upload LOI package',
    project: '1247 Elm Street',
    from: 'Action Center',
    fromRole: 'Ops',
    preview: 'Assigned to you · due in 2 days.',
    body: 'Upload LOI package for 1247 Elm Street is due in 2 days.\n\nRequired: signed LOI PDF, proof of funds letter, and entity W-9.',
    unread: true,
    receivedAt: '2026-08-19T08:00:00Z',
    deepLinkUrl: '/dashboard/projects',
    actionable: true,
  },
  {
    id: 'thread-5',
    tab: 'team',
    type: 'TEAM_INVITE',
    subject: 'Jordan joined the workspace',
    project: 'Team',
    from: 'PaperWorking Team',
    fromRole: 'Workspace',
    preview: 'Jordan Lee accepted Analyst invite.',
    body: 'Jordan Lee accepted the Analyst invite and now has access to shared projects in this workspace.',
    unread: false,
    receivedAt: '2026-08-16T11:20:00Z',
    deepLinkUrl: '/dashboard/team',
  },
  {
    id: 'thread-6',
    tab: 'opportunities',
    type: 'PHASE_TRANSITION',
    subject: 'New co-invest interest on 512 Oak Ridge',
    project: '512 Oak Ridge',
    from: 'Deals Marketplace',
    fromRole: 'Marketplace',
    preview: '2 investors requested term sheet access.',
    body: 'Two marketplace investors requested term sheet access for 512 Oak Ridge.\n\nReview their profiles in Marketplace before granting document vault access.',
    unread: true,
    receivedAt: '2026-08-19T18:05:00Z',
    deepLinkUrl: '/dashboard/marketplace',
    actionable: true,
  },
  {
    id: 'thread-7',
    tab: 'tasks',
    type: 'RECEIPT_APPROVAL',
    subject: 'Receipt approval needed — HVAC invoice',
    project: '88 Harbor Lane',
    from: 'Ops Ledger',
    fromRole: 'Finance',
    preview: '$2,480 invoice from CoolAir Pros awaiting approval.',
    body: 'HVAC invoice from CoolAir Pros ($2,480) needs approval before posting to the Hold ledger on 88 Harbor Lane.',
    unread: true,
    receivedAt: '2026-08-19T11:30:00Z',
    deepLinkUrl: '/dashboard/projects',
    actionable: true,
  },
  {
    id: 'thread-8',
    tab: 'system',
    type: 'DOCUMENT_SIGNED',
    subject: 'Closing disclosure signed',
    project: '512 Oak Ridge',
    from: 'DocuSign Bridge',
    fromRole: 'Documents',
    preview: 'Buyer countersigned CD · vault indexed.',
    body: 'Closing disclosure for 512 Oak Ridge was countersigned and indexed into the project vault.',
    unread: false,
    receivedAt: '2026-08-15T15:10:00Z',
    deepLinkUrl: '/dashboard/projects',
  },
];
