import { type NextRequest, NextResponse } from 'next/server';
import { buildMarketplaceProfileReadService } from '@/lib/api/handler-deps';
import { resolveAuthUserFromRequest } from '@/lib/api/server-session';
import { isDevAuthFailure, requireDevSessionAuth } from '@/lib/projects/dev-session-auth';
import { updateUserProfile } from '@/lib/settings/settings-store';
import { CANONICAL_REIL_33_KPI_METRICS } from '@/lib/profile/reil-track-record';

export const dynamic = 'force-dynamic';

const MAX_BIO_LENGTH = 600;

function str(value: unknown, max: number): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : '';
}

/** GET /api/marketplace/profile — self-scoped marketplace profile for authenticated user. */
export async function GET(request: Request) {
  const user = await resolveAuthUserFromRequest(request);
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const result = await buildMarketplaceProfileReadService().getMarketplaceProfile(user);
    return NextResponse.json(result);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      { error: 'Failed to fetch marketplace profile', details: message },
      { status: 500 },
    );
  }
}

export async function POST(request: NextRequest) {
  return PUT(request);
}

/** PUT /api/marketplace/profile — save the caller's public marketplace profile. */
export async function PUT(request: NextRequest) {
  const auth = await requireDevSessionAuth();
  if (isDevAuthFailure(auth)) {
    return NextResponse.json(auth.body, { status: auth.status });
  }

  let body: Record<string, unknown> = {};
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON payload' }, { status: 400 });
  }

  if (!body || typeof body !== 'object') {
    return NextResponse.json({ error: 'Invalid profile payload.' }, { status: 400 });
  }

  const displayName = str(body.displayName, 120);
  if (!displayName) {
    return NextResponse.json({ error: 'Display name is required.' }, { status: 400 });
  }

  const businessName = str(body.businessName, 120);
  const websiteUrl = str(body.websiteUrl, 300);
  if (websiteUrl && !/^https?:\/\//i.test(websiteUrl)) {
    return NextResponse.json(
      { error: 'Website must start with http:// or https://' },
      { status: 400 },
    );
  }

  const strategies = Array.isArray(body.strategies)
    ? body.strategies
        .filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0)
        .slice(0, 20)
        .map((entry) => entry.trim())
    : [];

  const patch: Record<string, unknown> = {
    displayName,
    businessName,
    companyName: businessName,
    headline: str(body.headline, 120),
    publicBio: str(body.publicBio, MAX_BIO_LENGTH),
    location: str(body.location, 120),
    websiteUrl,
    strategies,
    publicProfile: body.publicProfile === true,
    // Historical track record is generated by the REIL 33 Underwriting KPIs Engine (non-editable).
    aumCents: CANONICAL_REIL_33_KPI_METRICS.aumMillions * 1_000_000 * 100,
    avgRoiPct: CANONICAL_REIL_33_KPI_METRICS.avgRoiPct,
    equityMultiple: CANONICAL_REIL_33_KPI_METRICS.equityMultiple,
    dealCount: CANONICAL_REIL_33_KPI_METRICS.dealCount,
  };

  if (typeof body.avatarUrl === 'string') {
    patch.avatarUrl = body.avatarUrl;
  }

  try {
    const updated = await updateUserProfile(auth.uid, patch);
    return NextResponse.json({ success: true, profile: updated });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('[MarketplaceProfileAPI] Failed to update profile:', message);
    return NextResponse.json(
      { error: 'Unable to save profile. Please retry.' },
      { status: 500 },
    );
  }
}
