// ═══════════════════════════════════════════════════════
//  PaperWorking Glossary — Real Estate Investing Terms
//  Combines industry-standard RE terminology with
//  PaperWorking platform-specific vocabulary.
// ═══════════════════════════════════════════════════════

export interface GlossaryTerm {
  term: string;
  definition: string;
  category: GlossaryCategory;
  relatedTerms?: string[];
  platformFeature?: string; // Maps to a PaperWorking feature/tab
}

export type GlossaryCategory =
  | 'financial-metrics'
  | 'acquisition'
  | 'financing'
  | 'due-diligence'
  | 'rehab-construction'
  | 'exit-disposition'
  | 'legal-compliance'
  | 'platform';

export const GLOSSARY_CATEGORIES: { id: GlossaryCategory; label: string }[] = [
  { id: 'financial-metrics', label: 'Financial Metrics' },
  { id: 'acquisition', label: 'Acquisition & Sourcing' },
  { id: 'financing', label: 'Financing & Capital' },
  { id: 'due-diligence', label: 'Due Diligence' },
  { id: 'rehab-construction', label: 'Rehab & Construction' },
  { id: 'exit-disposition', label: 'Exit & Disposition' },
  { id: 'legal-compliance', label: 'Legal & Compliance' },
  { id: 'platform', label: 'PaperWorking Platform' },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── Financial Metrics ──
  {
    term: 'After-Repair Value (ARV)',
    definition: 'The estimated market value of a property after all planned renovations and repairs have been completed. Critical for fix-and-flip investors to determine if a project will generate enough equity to justify renovation costs.',
    category: 'financial-metrics',
    relatedTerms: ['70% Rule', 'CapEx', 'Scope of Work'],
  },
  {
    term: 'Cap Rate (Capitalization Rate)',
    definition: 'A percentage representing the expected annual return on a property based on its current market value, assuming an all-cash purchase. Formula: NOI ÷ Current Market Value. Used to compare the relative value and risk of different income-generating properties.',
    category: 'financial-metrics',
    relatedTerms: ['NOI', 'Cash-on-Cash Return'],
  },
  {
    term: 'Cash-on-Cash Return',
    definition: 'A percentage measuring the annual pre-tax cash flow received relative to the total cash invested. Formula: Annual Pre-Tax Cash Flow ÷ Total Cash Invested. Reflects the reality of using leverage.',
    category: 'financial-metrics',
    relatedTerms: ['Cap Rate', 'IRR', 'NOI'],
    platformFeature: 'Engine Room',
  },
  {
    term: 'Cost Basis',
    definition: 'The total amount of money invested in a property, including the purchase price, closing costs, and all capital improvements (CapEx). Used to calculate capital gains upon sale.',
    category: 'financial-metrics',
    relatedTerms: ['Capital Gains Tax', 'CapEx', 'Closing Costs'],
    platformFeature: 'Cost Basis Ledger',
  },
  {
    term: 'Debt Service Coverage Ratio (DSCR)',
    definition: 'A ratio measuring a property\'s ability to cover its debt obligations. Formula: NOI ÷ Annual Debt Service. A DSCR above 1.0 means the property generates enough income to cover its mortgage payments.',
    category: 'financial-metrics',
    relatedTerms: ['NOI', 'LTV'],
  },
  {
    term: 'Gross Rent Multiplier (GRM)',
    definition: 'A quick valuation metric calculated by dividing the property price by its gross annual rental income. Lower GRM generally indicates a better investment opportunity.',
    category: 'financial-metrics',
    relatedTerms: ['Cap Rate', 'NOI'],
  },
  {
    term: 'Internal Rate of Return (IRR)',
    definition: 'An annualized percentage representing the total expected return of an investment over its entire holding period, accounting for the time value of money. Considers cash flow, appreciation, and timing of all capital inflows and outflows.',
    category: 'financial-metrics',
    relatedTerms: ['Cash-on-Cash Return', 'ROI'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'Net Operating Income (NOI)',
    definition: 'The annual income generated by a property after deducting all operating expenses, but before accounting for financing costs, income taxes, and capital expenditures. Formula: Gross Operating Income – Operating Expenses.',
    category: 'financial-metrics',
    relatedTerms: ['Cap Rate', 'DSCR', 'Operating Expenses'],
    platformFeature: 'Engine Room',
  },
  {
    term: 'Return on Investment (ROI)',
    definition: 'The total percentage gain or loss on an investment relative to its cost. Formula: (Net Profit ÷ Total Investment) × 100. A broad measure of profitability.',
    category: 'financial-metrics',
    relatedTerms: ['IRR', 'Cash-on-Cash Return'],
    platformFeature: 'Exit Hub',
  },
  {
    term: '70% Rule',
    definition: 'A guideline for fix-and-flip investors stating that you should pay no more than 70% of a property\'s ARV minus the estimated repair costs. Formula: Maximum Purchase Price = (ARV × 0.70) – Repair Costs.',
    category: 'financial-metrics',
    relatedTerms: ['ARV', 'CapEx'],
  },
  // ── Acquisition & Sourcing ──
  {
    term: 'Comparable Sales (Comps)',
    definition: 'Recently sold properties similar in size, condition, and location used to estimate a subject property\'s fair market value. The foundation of most real estate appraisals.',
    category: 'acquisition',
    relatedTerms: ['ARV', 'Appraisal'],
  },
  {
    term: 'Earnest Money Deposit (EMD)',
    definition: 'A good-faith deposit made by a buyer to demonstrate serious intent to purchase. Typically 1-3% of the purchase price, held in escrow until closing. At risk if buyer defaults without a valid contingency.',
    category: 'acquisition',
    relatedTerms: ['Contingency', 'Escrow'],
    platformFeature: 'Negotiation Ledger',
  },
  {
    term: 'Letter of Intent (LOI)',
    definition: 'A non-binding document outlining the preliminary terms of a real estate transaction between buyer and seller before a formal purchase agreement is drafted.',
    category: 'acquisition',
    relatedTerms: ['Purchase Agreement', 'EMD'],
    platformFeature: 'Acquisition Panel',
  },
  {
    term: 'Off-Market Deal',
    definition: 'A property that is available for sale but not listed on the Multiple Listing Service (MLS). Often sourced through direct mail, wholesalers, or networking.',
    category: 'acquisition',
    relatedTerms: ['Wholesale', 'MLS'],
  },
  {
    term: 'Purchase Agreement',
    definition: 'A legally binding contract between buyer and seller that outlines the terms and conditions of a real estate transaction, including price, contingencies, and closing date.',
    category: 'acquisition',
    relatedTerms: ['EMD', 'Contingency', 'LOI'],
  },
  {
    term: 'Wholesale',
    definition: 'An investment strategy where a wholesaler contracts a property and then assigns the contract to an end buyer for a fee, without ever taking ownership of the property.',
    category: 'acquisition',
    relatedTerms: ['Assignment Fee', 'Off-Market Deal'],
  },
  // ── Financing & Capital ──
  {
    term: 'Bridge Loan',
    definition: 'A short-term loan (typically 6-24 months) used to "bridge" the gap between the purchase of a new property and the sale of an existing one, or until permanent financing is secured.',
    category: 'financing',
    relatedTerms: ['Hard Money Loan', 'LTV'],
    platformFeature: 'Capital & Evaluation',
  },
  {
    term: 'Capital Stack',
    definition: 'The full hierarchy of financing sources used to fund a real estate deal, typically ordered by seniority: senior debt, mezzanine debt, preferred equity, and common equity.',
    category: 'financing',
    relatedTerms: ['Syndication', 'Bridge Loan'],
    platformFeature: 'Capital & Evaluation',
  },
  {
    term: 'Hard Money Loan',
    definition: 'A short-term, asset-based loan from private lenders, secured by the property itself rather than the borrower\'s creditworthiness. Higher interest rates (8-15%) but faster approval.',
    category: 'financing',
    relatedTerms: ['Bridge Loan', 'Points', 'LTV'],
  },
  {
    term: 'Loan-to-Value Ratio (LTV)',
    definition: 'A percentage comparing the loan amount to the appraised property value. Formula: Loan Amount ÷ Property Value. Lower LTV = less lender risk = better loan terms.',
    category: 'financing',
    relatedTerms: ['DSCR', 'Hard Money Loan'],
  },
  {
    term: 'Points (Origination Points)',
    definition: 'Upfront fees charged by a lender, expressed as a percentage of the loan amount. One point equals 1% of the loan. Common in hard money lending.',
    category: 'financing',
    relatedTerms: ['Hard Money Loan', 'Closing Costs'],
  },
  {
    term: 'Syndication',
    definition: 'A method of pooling capital from multiple investors (Limited Partners) to fund a real estate deal, managed by a General Partner or Sponsor. Governed by SEC regulations.',
    category: 'financing',
    relatedTerms: ['Capital Stack', 'PPM', 'K-1'],
    platformFeature: 'Capital Syndicate',
  },
  // ── Due Diligence ──
  {
    term: 'Appraisal',
    definition: 'A professional, unbiased estimate of a property\'s fair market value, typically required by lenders before approving a mortgage loan.',
    category: 'due-diligence',
    relatedTerms: ['Comps', 'ARV'],
  },
  {
    term: 'Chain of Title',
    definition: 'The historical sequence of ownership transfers for a property, from the original grant to the current owner. A clean chain of title is essential for a valid transfer.',
    category: 'due-diligence',
    relatedTerms: ['Title Search', 'Title Insurance'],
    platformFeature: 'Purchase Panel',
  },
  {
    term: 'Contingency',
    definition: 'A clause in a purchase agreement that allows the buyer to back out of the deal without penalty if certain conditions are not met (e.g., inspection, financing, appraisal contingencies).',
    category: 'due-diligence',
    relatedTerms: ['EMD', 'Purchase Agreement'],
    platformFeature: 'Contingency Tracker',
  },
  {
    term: 'Phase I Environmental Assessment',
    definition: 'An investigation of a property\'s environmental condition, including historical land use, to identify potential contamination or hazardous materials. Required by most commercial lenders.',
    category: 'due-diligence',
    relatedTerms: ['Recognized Environmental Condition'],
    platformFeature: 'Zoning Scan Panel',
  },
  {
    term: 'Title Insurance',
    definition: 'An insurance policy that protects the buyer and/or lender against financial loss from defects in the title, such as liens, encumbrances, or ownership disputes.',
    category: 'due-diligence',
    relatedTerms: ['Chain of Title', 'Title Search'],
  },
  {
    term: 'Title Search',
    definition: 'An examination of public records to confirm the legal ownership of a property and identify any liens, encumbrances, or claims against it.',
    category: 'due-diligence',
    relatedTerms: ['Chain of Title', 'Title Insurance'],
  },
  // ── Rehab & Construction ──
  {
    term: 'Burn Rate',
    definition: 'The rate at which holding costs accumulate during a rehab project. Includes monthly payments for debt service, property taxes, insurance, and utilities.',
    category: 'rehab-construction',
    relatedTerms: ['Holding Costs', 'CapEx'],
    platformFeature: 'Hold Panel',
  },
  {
    term: 'Capital Expenditure (CapEx)',
    definition: 'Significant one-time expenses for property improvements that add value or extend the property\'s useful life, such as a new roof, HVAC system, or kitchen renovation.',
    category: 'rehab-construction',
    relatedTerms: ['Scope of Work', 'Cost Basis', 'ARV'],
    platformFeature: 'Hold Panel',
  },
  {
    term: 'Escrow Draw',
    definition: 'A disbursement of renovation funds held in escrow by a lender, released to the borrower upon completion and verification of specific construction milestones.',
    category: 'rehab-construction',
    relatedTerms: ['CapEx', 'Lien Waiver'],
    platformFeature: 'Hold Panel',
  },
  {
    term: 'Holding Costs',
    definition: 'Recurring monthly expenses incurred while owning a property, including mortgage payments, property taxes, insurance, utilities, and HOA fees.',
    category: 'rehab-construction',
    relatedTerms: ['Burn Rate', 'NOI'],
    platformFeature: 'Hold Panel',
  },
  {
    term: 'Lien Waiver',
    definition: 'A document signed by a contractor waiving their right to file a mechanic\'s lien against the property after receiving payment. Essential before authorizing draw payments.',
    category: 'rehab-construction',
    relatedTerms: ['Escrow Draw', 'Mechanic\'s Lien'],
    platformFeature: 'Vendor Portal',
  },
  {
    term: 'Scope of Work (SOW)',
    definition: 'A detailed document outlining all renovation tasks, materials, timelines, and costs for a rehab project. Used as the basis for contractor bids and milestone tracking.',
    category: 'rehab-construction',
    relatedTerms: ['CapEx', 'ARV'],
    platformFeature: 'Vendor Portal',
  },
  // ── Exit & Disposition ──
  {
    term: '1031 Exchange',
    definition: 'A tax-deferral strategy allowing an investor to sell a property and reinvest the proceeds into a "like-kind" property, deferring capital gains taxes. Must follow strict IRS timelines.',
    category: 'exit-disposition',
    relatedTerms: ['Capital Gains Tax', 'Cost Basis'],
  },
  {
    term: 'Capital Gains Tax',
    definition: 'A tax on the profit realized from the sale of a property. Short-term (held < 1 year) gains are taxed as ordinary income; long-term gains receive preferential rates.',
    category: 'exit-disposition',
    relatedTerms: ['Cost Basis', '1031 Exchange', 'Net Proceeds'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'Closing Disclosure (CD)',
    definition: 'A standardized five-page form detailing the final terms and costs of a mortgage loan. Replaced the HUD-1 for most residential transactions after 2015.',
    category: 'exit-disposition',
    relatedTerms: ['HUD-1', 'Closing Costs', 'Prorations'],
    platformFeature: 'Engine Room',
  },
  {
    term: 'HUD-1 Settlement Statement',
    definition: 'A document itemizing all charges and credits to buyer and seller in a real estate transaction. Still used in cash deals and commercial transactions.',
    category: 'exit-disposition',
    relatedTerms: ['Closing Disclosure', 'Prorations'],
  },
  {
    term: 'Net Proceeds',
    definition: 'The final amount received by the seller after deducting all selling costs, including agent commissions, closing costs, outstanding liens, and prorated expenses.',
    category: 'exit-disposition',
    relatedTerms: ['Capital Gains Tax', 'Prorations'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'Prorations',
    definition: 'The division of certain property expenses (taxes, insurance, HOA dues) between buyer and seller based on the closing date, ensuring each party pays only for their period of ownership.',
    category: 'exit-disposition',
    relatedTerms: ['Settlement Ledger', 'Closing Disclosure'],
    platformFeature: 'Exit Hub',
  },
  // ── Legal & Compliance ──
  {
    term: 'K-1 (Schedule K-1)',
    definition: 'An IRS tax form issued to partners in a partnership or members of an LLC, reporting their share of income, deductions, and credits for the tax year.',
    category: 'legal-compliance',
    relatedTerms: ['Syndication', 'LLC'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'LLC (Limited Liability Company)',
    definition: 'A business entity structure providing personal liability protection for its members. Common in real estate for holding individual properties or portfolios.',
    category: 'legal-compliance',
    relatedTerms: ['Series LLC', 'Operating Agreement'],
    platformFeature: 'Entity Management',
  },
  {
    term: 'Operating Agreement',
    definition: 'A legal document governing the internal operations of an LLC, including member roles, profit distribution, and decision-making authority.',
    category: 'legal-compliance',
    relatedTerms: ['LLC', 'Syndication'],
  },
  {
    term: 'Private Placement Memorandum (PPM)',
    definition: 'A legal document provided to prospective investors in a syndication, disclosing the terms, risks, and financial details of the investment offering. Required by SEC regulations.',
    category: 'legal-compliance',
    relatedTerms: ['Syndication', 'Capital Stack'],
    platformFeature: 'Document Vault',
  },
  {
    term: 'Series LLC',
    definition: 'A special form of LLC that allows multiple "series" or cells within a single entity, each with its own assets and liabilities. Useful for holding multiple properties.',
    category: 'legal-compliance',
    relatedTerms: ['LLC', 'Operating Agreement'],
  },
  // ── PaperWorking Platform Terms ──
  {
    term: 'Acquisition Panel',
    definition: 'The PaperWorking dashboard panel for Phase 1 of the investment lifecycle. Used to source properties, generate LOIs, submit offers, and manage your deal pipeline.',
    category: 'platform',
    platformFeature: 'Acquisition Panel',
  },
  {
    term: 'Capital Syndicate',
    definition: 'A PaperWorking feature that allows you to invite investors, collect soft commitments (Funding Pledges), and convert them into formal LOIs for a specific deal.',
    category: 'platform',
    relatedTerms: ['LOI', 'Syndication', 'Guest Portal'],
    platformFeature: 'Capital & Evaluation',
  },
  {
    term: 'Command Center',
    definition: 'The primary dashboard view in PaperWorking, displaying all seven deal lifecycle panels in a horizontally-scrollable interface for full deal visibility.',
    category: 'platform',
    platformFeature: 'Dashboard',
  },
  {
    term: 'Contingency Tracker',
    definition: 'A PaperWorking tool that monitors inspection, financing, and appraisal deadlines during Phase 2 (Purchase), with automated alerts to protect your EMD.',
    category: 'platform',
    relatedTerms: ['Contingency', 'EMD'],
    platformFeature: 'Purchase Panel',
  },
  {
    term: 'Cost Basis Ledger',
    definition: 'A PaperWorking financial report that automatically aggregates acquisition costs, CapEx, and holding costs from Phases 1-3 into your total cost basis for tax purposes.',
    category: 'platform',
    relatedTerms: ['Cost Basis', 'CapEx'],
    platformFeature: 'Engine Room',
  },
  {
    term: 'Deal Pipeline',
    definition: 'The PaperWorking panel that provides a Kanban-style view of all active prospects and deals, organized by status from initial lead through closing.',
    category: 'platform',
    platformFeature: 'Pipeline Panel',
  },
  {
    term: 'Deep Focus (Kanban View)',
    definition: 'An alternative PaperWorking dashboard mode that displays all projects in a vertical Kanban board layout, optimized for focused project management.',
    category: 'platform',
    platformFeature: 'Dashboard',
  },
  {
    term: 'Document Vault',
    definition: 'PaperWorking\'s secure file storage system where users upload contracts, PPMs, closing documents, and other sensitive files with role-based access controls.',
    category: 'platform',
    relatedTerms: ['RBAC', 'PPM'],
    platformFeature: 'Document Vault',
  },
  {
    term: 'Engine Room',
    definition: 'The PaperWorking panel housing financial reporting tools including P&L statements, cost basis ledgers, bank feed reconciliation, and tax export functionality.',
    category: 'platform',
    relatedTerms: ['Cost Basis Ledger', 'P&L'],
    platformFeature: 'Engine Room',
  },
  {
    term: 'Exit Hub',
    definition: 'The Phase 4 PaperWorking panel for managing property disposition, including settlement ledgers, net proceeds calculations, capital gains estimation, and investor distributions.',
    category: 'platform',
    relatedTerms: ['Net Proceeds', 'Capital Gains Tax'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'Field Manager',
    definition: 'A PaperWorking portal for general contractors to mark rehab tasks as complete, upload inspection photos, and submit invoices for milestone-based payment approval.',
    category: 'platform',
    relatedTerms: ['Scope of Work', 'Escrow Draw'],
    platformFeature: 'Field Manager',
  },
  {
    term: 'Funding Pledge',
    definition: 'A soft capital commitment from an investor recorded in PaperWorking before a formal LOI is generated. Tracks investor interest and projected capital availability.',
    category: 'platform',
    relatedTerms: ['LOI', 'Capital Syndicate'],
    platformFeature: 'Capital & Evaluation',
  },
  {
    term: 'Guest Portal',
    definition: 'A secure, read-only interface in PaperWorking where external parties (investors, attorneys, accountants) can review documents and sign LOIs without full platform access.',
    category: 'platform',
    relatedTerms: ['RBAC', 'Capital Syndicate'],
  },
  {
    term: 'Hold Panel',
    definition: 'The Phase 3 PaperWorking panel for tracking rehab progress, holding costs, burn rates, contractor milestones, and material procurement during the renovation period.',
    category: 'platform',
    relatedTerms: ['Burn Rate', 'Holding Costs', 'CapEx'],
    platformFeature: 'Hold Panel',
  },
  {
    term: 'Negotiation Ledger',
    definition: 'A PaperWorking feature that tracks all offer and counter-offer activity, including EMD status, for a specific property during the acquisition phase.',
    category: 'platform',
    relatedTerms: ['EMD', 'LOI'],
    platformFeature: 'Acquisition Panel',
  },
  {
    term: 'Phase Transition',
    definition: 'The act of advancing a deal from one lifecycle phase to the next in PaperWorking (e.g., Acquisition → Purchase). Requires specific conditions to be met before unlocking.',
    category: 'platform',
    relatedTerms: ['Phase Gate'],
    platformFeature: 'Dashboard',
  },
  {
    term: 'Purchase Panel',
    definition: 'The Phase 2 PaperWorking panel for managing due diligence, contingency deadlines, title searches, inspections, appraisals, and the closing document checklist.',
    category: 'platform',
    relatedTerms: ['Contingency Tracker', 'Chain of Title'],
    platformFeature: 'Purchase Panel',
  },
  {
    term: 'Role-Based Access Control (RBAC)',
    definition: 'PaperWorking\'s permission system that restricts data visibility based on a user\'s assigned role (Admin, Lead Investor, Accountant, Contractor, Guest).',
    category: 'platform',
    relatedTerms: ['Guest Portal', 'Document Vault'],
    platformFeature: 'Settings',
  },
  {
    term: 'Settlement Ledger',
    definition: 'A PaperWorking tool in the Exit Hub that centralizes all final transaction costs, buyer/seller credits, and prorated expenses for closing.',
    category: 'platform',
    relatedTerms: ['Prorations', 'Net Proceeds'],
    platformFeature: 'Exit Hub',
  },
  {
    term: 'Vendor Portal',
    definition: 'A PaperWorking interface where approved vendors (contractors, inspectors, appraisers) submit bids, upload W-9s, certificates of insurance, and lien waivers.',
    category: 'platform',
    relatedTerms: ['Lien Waiver', 'Scope of Work'],
    platformFeature: 'Vendor Portal',
  },
].sort((a, b) => a.term.localeCompare(b.term));
