import { Metadata } from 'next';
import LandingHeader from '@/components/landing/LandingHeader';
import LandingFooter from '@/components/landing/LandingFooter';

export const metadata: Metadata = {
  title: 'Terms of Service — PaperWorking',
  description: 'Terms of Service governing your use of the PaperWorking platform.',
};

const SECTIONS = [
  {
    heading: '1. Acceptance of Terms',
    body: 'By accessing or using PaperWorking, you agree to be bound by these Terms of Service and all applicable laws and regulations.',
  },
  {
    heading: '2. Use of Service',
    body: 'PaperWorking is a real estate investment operations platform. You agree to use the service only for lawful purposes and in accordance with these terms.',
  },
  {
    heading: '3. Data Ownership & Retention',
    body: 'You retain 100% ownership of all deal documents, financial data, spreadsheets, and files you upload to the platform. PaperWorking claims no rights, title, or interest in your data. In the event of account deletion, we purge all project assets within 24 hours, subject to standard 7-year regulatory retention of audit logs.',
  },
  {
    heading: '4. Third-Party Vendor Disclaimer',
    body: 'PaperWorking provides a vendor marketplace directory and messaging platform as a convenience. PaperWorking does not vet vendors, check credentials, or verify licenses. You must independently vet, verify, and contract any vendor you decide to do business with. PaperWorking is not liable for vendor performance or contract disputes.',
  },
  {
    heading: '5. Informational Metrics Disclaimer',
    body: 'All metrics, insights, DSCR calculators, Cap Rate charts, P&L reports, and financial insights generated by the platform are for informational and educational purposes only. They do not constitute financial, investment, legal, or tax advice. You must consult with certified CPAs, attorneys, or qualified investment brokers before executing any transactions.',
  },
  {
    heading: '6. Limitation of Liability',
    body: 'PaperWorking is provided "as is." We make no warranties regarding accuracy of financial calculations or market data. Under no circumstances will PaperWorking be liable for any direct, indirect, incidental, or consequential damages resulting from platform usage.',
  },
  {
    heading: '7. Arbitration & Delaware Jurisdiction',
    body: 'Any disputes arising out of these Terms or use of the service will be resolved by binding arbitration in accordance with AAA rules, rather than in court. These Terms are governed by and construed under the laws of the State of Delaware, without regard to conflicts of law principles.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-on-surface dark">
      <LandingHeader />

      <main className="max-w-3xl mx-auto px-6 md:px-margin-desktop pt-32 pb-24">
        {/* Hero */}
        <p className="font-label-sm text-label-sm text-primary uppercase tracking-widest mb-4">
          Legal
        </p>
        <h1 className="font-headline-lg text-headline-lg text-on-surface tracking-tight mb-3">
          Terms of Service
        </h1>
        <p className="font-body-sm text-body-sm text-on-surface-variant mb-16">
          Last updated May 2026
        </p>

        {/* Content sections */}
        <div className="space-y-10">
          {SECTIONS.map((s) => (
            <section
              key={s.heading}
              className="rounded-2xl p-8 sm:p-10"
              style={{
                background: 'linear-gradient(135deg, rgba(34,43,50,0.4), rgba(20,29,35,0.8))',
                backdropFilter: 'blur(16px)',
                WebkitBackdropFilter: 'blur(16px)',
                borderTop: '1px solid rgba(255,255,255,0.12)',
                borderLeft: '1px solid rgba(255,255,255,0.12)',
              }}
            >
              <h2 className="font-label-md text-label-md text-on-surface mb-4">
                {s.heading}
              </h2>
              <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
                {s.body}
              </p>
            </section>
          ))}

          {/* Contact section */}
          <section
            className="rounded-2xl p-8 sm:p-10"
            style={{
              background: 'linear-gradient(135deg, rgba(34,43,50,0.4), rgba(20,29,35,0.8))',
              backdropFilter: 'blur(16px)',
              WebkitBackdropFilter: 'blur(16px)',
              borderTop: '1px solid rgba(255,255,255,0.12)',
              borderLeft: '1px solid rgba(255,255,255,0.12)',
            }}
          >
            <h2 className="font-label-md text-label-md text-on-surface mb-4">
              8. Contact
            </h2>
            <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
              For questions about these terms, contact{' '}
              <a
                href="mailto:legal@paperworking.co"
                className="text-primary hover:underline decoration-primary/50 transition-colors"
              >
                legal@paperworking.co
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
