#!/usr/bin/env npx tsx
/**
 * scripts/stripe-setup.ts
 *
 * Run with: npx tsx scripts/stripe-setup.ts
 *
 * Creates 3 Stripe products with monthly + annual prices for PaperWorking.
 * Outputs the resulting price IDs in .env.local format so you can paste them
 * directly into your environment configuration.
 *
 * ┌──────────────┬──────────┬────────────┐
 * │ Product      │ Monthly  │ Annual     │
 * ├──────────────┼──────────┼────────────┤
 * │ Solo         │ $39/mo   │ $390/yr    │
 * │ Investor     │ $89/mo   │ $890/yr    │
 * │ Team         │ $199/mo  │ $1,990/yr  │
 * └──────────────┴──────────┴────────────┘
 *
 * IMPORTANT:
 *   - Requires STRIPE_SECRET_KEY to be set in your environment
 *   - Safe to run multiple times — uses idempotency keys
 *   - Does NOT modify .env.local automatically
 *   - Products are created in the Stripe mode (test/live) matching your key
 */

import Stripe from 'stripe';

/* ═══════════════════════════════════════════════════════
   Configuration
   ═══════════════════════════════════════════════════════ */

interface PlanDefinition {
  name: string;
  /** Internal ID for env var naming (matches PLAN_CATALOG keys) */
  envKey: string;
  description: string;
  monthlyPriceCents: number;
  annualPriceCents: number;
  features: string[];
  /** Maps to PlanId in src/lib/stripe/plans.ts */
  metadata: { planId: string; canonicalName: string };
}

const PLANS: PlanDefinition[] = [
  {
    name: 'PaperWorking Solo',
    envKey: 'VENDOR',
    description: 'For solo professionals — lawyers, loan processors, contractors, appraisers — who want deal flow from active investors.',
    monthlyPriceCents: 3900,
    annualPriceCents: 39000,
    features: [
      'Localized Deal Request Pipeline',
      'Closing Room Document Access',
      'Client Communication Hub',
      'Title Search & Verification Tools',
      'Report Upload & Verification',
    ],
    metadata: { planId: 'vendor', canonicalName: 'Vendor Network' },
  },
  {
    name: 'PaperWorking Investor',
    envKey: 'INDIVIDUAL',
    description: 'Built for solo investors who want full pipeline visibility without a team subscription.',
    monthlyPriceCents: 8900,
    annualPriceCents: 89000,
    features: [
      'Unlimited Property Tracking',
      'Full 4-Phase Lifecycle Kanban',
      'Engine Room Ledger',
      'Standard Financial Reports',
      'Holding Cost Clock',
    ],
    metadata: { planId: 'individual', canonicalName: 'Individual' },
  },
  {
    name: 'PaperWorking Team',
    envKey: 'TEAM',
    description: 'For investor teams who need role-based access, shared workflows, and complete financial separation.',
    monthlyPriceCents: 19900,
    annualPriceCents: 199000,
    features: [
      'Everything in Investor',
      'Team Member Invites (Agents, GCs)',
      'Granular Role-Based Data Isolation',
      'Advanced Vendor Management',
      'Google Drive Provisioning',
      'Advanced Financial Reports',
      'Escrow Integration & API Access',
    ],
    metadata: { planId: 'team', canonicalName: 'Team' },
  },
];

/* ═══════════════════════════════════════════════════════
   Main
   ═══════════════════════════════════════════════════════ */

async function main() {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) {
    console.error('❌ STRIPE_SECRET_KEY is not set. Export it first:');
    console.error('   export STRIPE_SECRET_KEY=sk_test_...');
    process.exit(1);
  }

  const isLive = key.startsWith('sk_live_');
  console.log(`\n🔑 Using ${isLive ? '🔴 LIVE' : '🟢 TEST'} Stripe key\n`);

  if (isLive) {
    console.warn('⚠️  WARNING: You are using a LIVE Stripe key.');
    console.warn('   Products and prices will be created in your LIVE account.');
    console.warn('   Press Ctrl+C within 5 seconds to cancel.\n');
    await new Promise((resolve) => setTimeout(resolve, 5000));
  }

  const stripe = new Stripe(key, { apiVersion: '2025-04-30.basil' as any });

  const envLines: string[] = [
    '# ─── Stripe Price IDs ───────────────────────────────',
    `# Generated by scripts/stripe-setup.ts on ${new Date().toISOString()}`,
    `# Mode: ${isLive ? 'LIVE' : 'TEST'}`,
    '',
  ];

  for (const plan of PLANS) {
    console.log(`━━━ Creating: ${plan.name} ━━━`);

    // ── Create Product ──────────────────────────────────
    const product = await stripe.products.create(
      {
        name: plan.name,
        description: plan.description,
        metadata: {
          ...plan.metadata,
          features: JSON.stringify(plan.features),
          managedBy: 'scripts/stripe-setup.ts',
        },
      },
      { idempotencyKey: `pw-product-${plan.metadata.planId}-v1` }
    );
    console.log(`  ✅ Product: ${product.id}`);

    // ── Create Monthly Price ────────────────────────────
    const monthlyPrice = await stripe.prices.create(
      {
        product: product.id,
        unit_amount: plan.monthlyPriceCents,
        currency: 'usd',
        recurring: { interval: 'month' },
        metadata: {
          planId: plan.metadata.planId,
          interval: 'monthly',
        },
      },
      { idempotencyKey: `pw-price-${plan.metadata.planId}-monthly-v1` }
    );
    console.log(`  ✅ Monthly: ${monthlyPrice.id}  ($${(plan.monthlyPriceCents / 100).toFixed(2)}/mo)`);

    // ── Create Annual Price ─────────────────────────────
    const annualPrice = await stripe.prices.create(
      {
        product: product.id,
        unit_amount: plan.annualPriceCents,
        currency: 'usd',
        recurring: { interval: 'year' },
        metadata: {
          planId: plan.metadata.planId,
          interval: 'annual',
        },
      },
      { idempotencyKey: `pw-price-${plan.metadata.planId}-annual-v1` }
    );
    console.log(`  ✅ Annual:  ${annualPrice.id}  ($${(plan.annualPriceCents / 100).toFixed(2)}/yr)`);

    // ── Collect env vars ────────────────────────────────
    envLines.push(`STRIPE_PRICE_${plan.envKey}_MONTHLY=${monthlyPrice.id}`);
    envLines.push(`STRIPE_PRICE_${plan.envKey}_ANNUAL=${annualPrice.id}`);
    envLines.push('');
  }

  // ── Create Referral Coupon ────────────────────────────
  console.log('━━━ Creating Referral Coupon ━━━');
  try {
    const coupon = await stripe.coupons.create(
      {
        id: 'referral-one-month-free',
        duration: 'once',
        percent_off: 100,
        name: 'Referral - 1 Month Free',
        metadata: {
          managedBy: 'scripts/stripe-setup.ts',
        },
      },
      { idempotencyKey: 'pw-coupon-referral-one-month-free-v1' }
    );
    console.log(`  ✅ Coupon:   ${coupon.id} (${coupon.name})`);
  } catch (err: any) {
    console.error('  ❌ Failed to create coupon:', err.message);
  }

  // ── Output ──────────────────────────────────────────
  console.log('\n\n' + '═'.repeat(60));
  console.log('  Copy these into your .env.local:');
  console.log('═'.repeat(60) + '\n');
  console.log(envLines.join('\n'));
  console.log('\n' + '═'.repeat(60));
  console.log('  ✅ All products and prices created successfully!');
  console.log('═'.repeat(60) + '\n');
}

main().catch((err) => {
  console.error('❌ Fatal error:', err.message);
  process.exit(1);
});
