import React from 'react';
import fs from 'fs';
import path from 'path';
import { describe, expect, it, jest } from '@jest/globals';
import { renderToString } from 'react-dom/server';
import ConversationalStepWizard from '../../components/projects/ConversationalStepWizard.js';
import AcquisitionWorkspaceView from '../../components/projects/AcquisitionWorkspaceView.js';
import FundWorkspaceView from '../../components/projects/FundWorkspaceView.js';
import HoldWorkspaceView from '../../components/projects/HoldWorkspaceView.js';
import ExitWorkspaceView from '../../components/projects/ExitWorkspaceView.js';
import {
  ACQUISITION_CONVERSATIONAL_STEPS,
  FUND_CONVERSATIONAL_STEPS,
  HOLD_CONVERSATIONAL_STEPS,
  EXIT_CONVERSATIONAL_STEPS,
  getConversationalStepsForPhase,
  getConversationalStep,
} from '../../lib/projects/reil-conversational-steps.js';
import type { ProjectWorkspace } from '../../lib/projects/types.js';

const mockProject: ProjectWorkspace = {
  id: 'deal-lifecycle',
  project_id: 'deal-lifecycle',
  propertyName: '1247 Elm Street',
  address: '1247 Elm Street, Austin, TX 78702',
  property_address: '1247 Elm Street, Austin, TX 78702',
  city: 'Austin, TX',
  currentPhase: 'acquisition',
  phase: 'acquisition',
  status: 'Underwriting',
  dispositionType: 'SALE',
  purchasePrice: 485000,
  purchase_price: 485000,
  rehab_costs: 62000,
  exit_strategy: 'Fix & Flip',
  entity_type: 'LLC',
  phase_completion_pct: 25,
  estimatedIrr: 0.184,
  dealId: null,
  dealSlug: null,
  dealAddress: null,
  storage_used_bytes: 1000,
  storageQuotaBytes: 536870912,
  todos: [],
  documents: [],
  acquisitionStatus: 'under_contract',
  tasks: [
    {
      id: 'acq-step-1-lead',
      title: 'Lead Intake & Property Identification',
      status: 'complete',
      assignedTo: 'Sarah Chen',
      dueDate: '2026-04-15',
      isAutoGenerated: true,
    },
    {
      id: 'acq-step-2-underwriting',
      title: 'Financial Valuation & Deal Underwriting',
      status: 'pending',
      assignedTo: 'Marcus Vance',
      dueDate: '2026-04-20',
      isAutoGenerated: true,
    },
  ],
  teamMembers: [
    {
      id: 'team-1',
      name: 'Sarah Chen',
      email: 'sarah@capital.com',
      role: 'Acquisitions Director',
    },
    {
      id: 'team-2',
      name: 'Marcus Vance',
      email: 'marcus@builds.com',
      role: 'General Contractor',
    },
  ],
  phaseAssignees: {
    acquisition: {
      id: 'team-1',
      name: 'Sarah Chen',
      email: 'sarah@capital.com',
      role: 'Acquisitions Director',
    },
  },
  contingencies: [],
};

describe('Conversational TurboTax/Clerky REIL Step Wizard & Question Engine', () => {
  describe('Canonical REIL Conversational Steps Definitions', () => {
    it('defines 8 canonical acquisition steps with conversational phrasing and legal rationale', () => {
      expect(ACQUISITION_CONVERSATIONAL_STEPS).toHaveLength(8);

      const expectedTitles = [
        'Lead Intake & Property Identification',
        'Financial Valuation & Deal Underwriting',
        'Letter of Intent & Offer Submission',
        'Negotiation & Counteroffer',
        'Purchase & Sale Agreement Execution',
        'Due Diligence & Inspections',
        'Clear to Close & Financing',
        'Settlement & Deed Recordation',
      ];

      ACQUISITION_CONVERSATIONAL_STEPS.forEach((step, index) => {
        expect(step.stepNumber).toBe(index + 1);
        expect(step.title).toBe(expectedTitles[index]);
        expect(step.conversationalQuestion.length).toBeGreaterThan(15);
        expect(step.whyThisMatters.length).toBeGreaterThan(25);
        expect(step.requiredDocuments.length).toBeGreaterThan(0);
        expect(step.defaultRole.length).toBeGreaterThan(0);
        expect(step.actionLabel.length).toBeGreaterThan(0);
        expect(step.inputs.length).toBeGreaterThan(0);
      });
    });

    it('defines 6 canonical fund/purchase steps', () => {
      expect(FUND_CONVERSATIONAL_STEPS).toHaveLength(6);

      const expectedTitles = [
        'Lender Term Sheet',
        'Earnest Money Deposit',
        'Narrative Appraisal & Environmental',
        'Title & Liens Clearance',
        'Insurance Binder & Entity Docs',
        'Closing Disclosure & Escrow Wire',
      ];

      FUND_CONVERSATIONAL_STEPS.forEach((step, index) => {
        expect(step.stepNumber).toBe(index + 1);
        expect(step.title).toBe(expectedTitles[index]);
        expect(step.conversationalQuestion.length).toBeGreaterThan(15);
        expect(step.whyThisMatters.length).toBeGreaterThan(25);
        expect(step.requiredDocuments.length).toBeGreaterThan(0);
      });
    });

    it('defines 5 canonical hold steps', () => {
      expect(HOLD_CONVERSATIONAL_STEPS).toHaveLength(5);

      const expectedTitles = [
        'Property Takeover & Utilities',
        'Contractor Scope Lock & Bids',
        'Construction Milestones & Lien Waivers',
        'Tenant Placement & Lease',
        'Operating Accounting & Holding Costs',
      ];

      HOLD_CONVERSATIONAL_STEPS.forEach((step, index) => {
        expect(step.stepNumber).toBe(index + 1);
        expect(step.title).toBe(expectedTitles[index]);
        expect(step.conversationalQuestion.length).toBeGreaterThan(15);
        expect(step.whyThisMatters.length).toBeGreaterThan(25);
        expect(step.requiredDocuments.length).toBeGreaterThan(0);
      });
    });

    it('defines 4 canonical exit steps', () => {
      expect(EXIT_CONVERSATIONAL_STEPS).toHaveLength(4);

      const expectedTitles = [
        'Strategy Determination & Valuation',
        'Marketing Launch & OM',
        'Buyer Offer Selection & PSA',
        'Realized Return Reconciliation & Distribution',
      ];

      EXIT_CONVERSATIONAL_STEPS.forEach((step, index) => {
        expect(step.stepNumber).toBe(index + 1);
        expect(step.title).toBe(expectedTitles[index]);
        expect(step.conversationalQuestion.length).toBeGreaterThan(15);
        expect(step.whyThisMatters.length).toBeGreaterThan(25);
        expect(step.requiredDocuments.length).toBeGreaterThan(0);
      });
    });

    it('helpers correctly retrieve steps by phase and step number or id', () => {
      const acqSteps = getConversationalStepsForPhase('acquisition');
      expect(acqSteps).toHaveLength(8);

      const step1 = getConversationalStep('acquisition', 1);
      expect(step1?.title).toBe('Lead Intake & Property Identification');

      const stepByString = getConversationalStep('acquisition', 'acq-step-3-loi');
      expect(stepByString?.title).toBe('Letter of Intent & Offer Submission');
    });
  });

  describe('ConversationalStepWizard Component Rendering', () => {
    it('renders Phase Leadership Banner with active phase lead and Change Lead button', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('data-testid="phase-leadership-banner"');
      expect(html).toContain('Phase Leadership');
      expect(html).toContain('Phase Lead:');
      expect(html).toContain('Sarah Chen');
      expect(html).toContain('data-testid="change-phase-lead-button"');
      expect(html).toContain('Change Phase Lead');
    });

    it('renders dual-mode switcher with Conversational Walkthrough and Executive Workspace', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('data-testid="active-conversational-mode-button"');
      expect(html).toContain('Conversational Walkthrough');
      expect(html).toContain('data-testid="switch-executive-view-button"');
      expect(html).toContain('Executive Workspace →');
    });

    it('renders step progress bar and clickable navigation pills', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('Acquisition Lifecycle Milestones: Step 1 of 8');
      expect(html).toContain('1 of 8 Completed (13%)');
      expect(html).toContain('data-testid="step-pill-1"');
      expect(html).toContain('data-testid="step-pill-2"');
      expect(html).toContain('data-testid="step-pill-8"');
    });

    it('renders conversational question, why this matters educational section, and document slot', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('data-testid="conversational-step-badge"');
      expect(html).toContain('Step 1 of 8 · Lead Intake &amp; Property Identification');
      expect(html).toContain('Verified Complete');
      expect(html).toContain('data-testid="conversational-step-question"');
      expect(html).toContain('Where is the property located, who is the seller, and what is the asking price?');
      expect(html).toContain('Why this matters (Legal &amp; Financial Rationale)');
      expect(html).toContain('Accurate property sourcing and seller identification establish the legal baseline');
      expect(html).toContain('data-testid="step-document-slot"');
      expect(html).toContain('Required Phase Documentation');
      expect(html).toContain('Open in Document Vault →');
      expect(html).toContain('Property Flier or OM');
    });

    it('renders embedded step assignee card with assign/reassign trigger', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('data-testid="step-assignee-card"');
      expect(html).toContain('Step Assigned Lead');
      expect(html).toContain('Sarah Chen');
      expect(html).toContain('sarah@capital.com');
      expect(html).toContain('data-testid="assign-step-member-button"');
      expect(html).toContain('Reassign / Invite Member');
    });

    it('renders response form and navigation bar with minimum 44px buttons', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProject.teamMembers}
        />
      );

      expect(html).toContain('data-testid="step-response-form"');
      expect(html).toContain('Step Input &amp; Execution Form');
      expect(html).toContain('Save Progress');
      expect(html).toContain('← Previous Step');
      expect(html).toContain('Next Step →');
      expect(html).toContain('data-testid="mark-step-complete-button"');
      expect(html).toContain('min-h-[44px]');
      expect(html).toContain('rounded-none');
    });
  });

  describe('Workspace Views Integration & Mode Switching', () => {
    it('AcquisitionWorkspaceView renders top mode switcher toggle bar', () => {
      const html = renderToString(
        <AcquisitionWorkspaceView project={mockProject} onUpdateProject={() => {}} />
      );

      expect(html).toContain('data-testid="toggle-conversational-view"');
      expect(html).toContain('data-testid="toggle-executive-view"');
      expect(html).toContain('Acquisition Phase Mode');
    });

    it('FundWorkspaceView renders top mode switcher toggle bar', () => {
      const html = renderToString(
        <FundWorkspaceView project={mockProject} onUpdateProject={() => {}} />
      );

      expect(html).toContain('data-testid="toggle-conversational-view"');
      expect(html).toContain('data-testid="toggle-executive-view"');
      expect(html).toContain('Fund Phase Mode');
    });

    it('HoldWorkspaceView renders top mode switcher toggle bar', () => {
      const html = renderToString(
        <HoldWorkspaceView project={mockProject} onUpdateProject={() => {}} />
      );

      expect(html).toContain('data-testid="toggle-conversational-view"');
      expect(html).toContain('data-testid="toggle-executive-view"');
      expect(html).toContain('Hold Phase Mode');
    });

    it('ExitWorkspaceView renders top mode switcher toggle bar', () => {
      const html = renderToString(
        <ExitWorkspaceView project={mockProject} onUpdateProject={() => {}} />
      );

      expect(html).toContain('data-testid="toggle-conversational-view"');
      expect(html).toContain('data-testid="toggle-executive-view"');
      expect(html).toContain('Exit Phase Mode');
    });
  });

  describe('Anti-Slop Compliance Check', () => {
    it('enforces zero forbidden terms and zero em-dashes across conversational wizard code', () => {
      const resolveFile = (subpath: string) => {
        const p1 = path.resolve(process.cwd(), subpath);
        if (fs.existsSync(p1)) return fs.readFileSync(p1, 'utf8');
        const p2 = path.resolve(process.cwd(), 'apps/web', subpath);
        if (fs.existsSync(p2)) return fs.readFileSync(p2, 'utf8');
        throw new Error(`File not found: ${subpath}`);
      };

      const stepDefs = resolveFile('lib/projects/reil-conversational-steps.ts');
      const wizardComponent = resolveFile('components/projects/ConversationalStepWizard.tsx');

      // Check forbidden term
      const forbiddenPattern = new RegExp(['s', 'p', 'o', 'n', 's', 'o', 'r'].join(''), 'i');
      expect(stepDefs).not.toMatch(forbiddenPattern);
      expect(wizardComponent).not.toMatch(forbiddenPattern);

      // Check em-dash
      const emDashChar = String.fromCharCode(8212);
      expect(stepDefs.includes(emDashChar)).toBe(false);
      expect(wizardComponent.includes(emDashChar)).toBe(false);
    });
  });
});
