import React from 'react';
import { describe, expect, it, jest } from '@jest/globals';
import { renderToString } from 'react-dom/server';
import AssignOrInviteModal from '../../components/projects/AssignOrInviteModal.js';
import AcquisitionWorkspaceView from '../../components/projects/AcquisitionWorkspaceView.js';
import FundWorkspaceView from '../../components/projects/FundWorkspaceView.js';
import HoldWorkspaceView from '../../components/projects/HoldWorkspaceView.js';
import ExitWorkspaceView from '../../components/projects/ExitWorkspaceView.js';
import type { ProjectWorkspace } from '../../lib/projects/types.js';
import { POST as handleInvitePost } from '../../app/api/invites/route.js';
import { getSeedProjectById, SEED_PROJECTS } from '../../lib/projects/seed-data.js';
import { sentEmailsForTesting, __clearSentEmailsForTesting } from '../../lib/email/sendgrid-service.js';

const mockProject: ProjectWorkspace = {
  id: 'deal-lifecycle',
  project_id: 'deal-lifecycle',
  propertyName: '1247 Elm Street',
  address: '1247 Elm Street, Austin, TX 78702',
  property_address: '1247 Elm Street, Austin, TX 78702',
  city: 'Austin, TX',
  currentPhase: 'acquisition',
  phase: 'acquisition',
  status: 'Underwriting',
  dispositionType: 'SALE',
  purchasePrice: 485000,
  purchase_price: 485000,
  rehab_costs: 62000,
  exit_strategy: 'Fix & Flip',
  entity_type: 'LLC',
  phase_completion_pct: 42,
  estimatedIrr: 0.184,
  dealId: null,
  dealSlug: null,
  dealAddress: null,
  storage_used_bytes: 1000,
  storageQuotaBytes: 536870912,
  todos: [],
  documents: [],
  acquisitionStatus: 'under_contract',
  tasks: [
    {
      id: 'task-title-search',
      title: 'Preliminary Title Search & Commitment',
      status: 'pending',
      assignedTo: 'Lead Underwriter',
      dueDate: '2026-04-15',
      isAutoGenerated: true,
    },
    {
      id: 'task-environmental',
      title: 'Phase I Environmental Site Assessment',
      status: 'pending',
      assignedTo: '',
      dueDate: '2026-04-20',
      isAutoGenerated: true,
    },
  ],
  teamMembers: [
    {
      id: 'team-1',
      name: 'Sarah Chen',
      email: 'sarah@capital.com',
      role: 'Acquisitions Director',
    },
    {
      id: 'team-2',
      name: 'Marcus Vance',
      email: 'marcus@builds.com',
      role: 'General Contractor',
    },
  ],
  contingencies: [],
};

describe('REIL Task Team Assignment and Email Invitation Suite', () => {
  it('renders AssignOrInviteModal with existing team members and invite form', () => {
    const html = renderToString(
      <AssignOrInviteModal
        isOpen={true}
        onClose={() => {}}
        projectId="deal-lifecycle"
        projectName="1247 Elm Street"
        task={{
          id: 'task-environmental',
          title: 'Phase I Environmental Site Assessment',
          assignedTo: '',
        }}
        existingMembers={mockProject.teamMembers}
        onAssignExisting={() => {}}
        onMemberInvitedAndAssigned={() => {}}
      />
    );

    expect(html).toContain('data-testid="assign-or-invite-modal"');
    expect(html).toContain('Assign REIL Task');
    expect(html).toContain('Phase I Environmental Site Assessment');
    expect(html).toContain('Project Team (');
    expect(html).toContain('+ Invite New Member via Email');
    expect(html).toContain('Sarah Chen');
    expect(html).toContain('Marcus Vance');
    expect(html).toContain('data-testid="assign-button-Sarah Chen"');
    expect(html).toContain('data-testid="assign-button-Marcus Vance"');
  });

  it('AcquisitionWorkspaceView renders "+ Invite via Email..." and assign trigger button for tasks', () => {
    const html = renderToString(
      <AcquisitionWorkspaceView
        project={mockProject}
        onUpdateProject={() => {}}
      />
    );

    expect(html).toContain('Preliminary Title Search &amp; Commitment');
    expect(html).toContain('+ Invite via Email...');
    expect(html).toContain('data-testid="open-assign-modal-task-title-search"');
  });

  it('FundWorkspaceView renders "+ Invite via Email..." in task selector and modal button', () => {
    const html = renderToString(
      <FundWorkspaceView
        project={mockProject}
        onUpdateProject={() => {}}
      />
    );

    expect(html).toContain('+ Invite via Email...');
    expect(html).toContain('data-testid="open-assign-modal-task-title-search"');
  });

  it('HoldWorkspaceView renders assign/invite triggers on Scope of Work contractor cells', () => {
    const html = renderToString(
      <HoldWorkspaceView
        project={mockProject}
        onUpdateProject={() => {}}
      />
    );

    expect(html).toContain('data-testid="assign-sow-sow-1"');
    expect(html).toContain('Apex Demo Services LLC');
  });

  it('ExitWorkspaceView renders Exit Disposition Milestones & Task Assignments with invite options', () => {
    const html = renderToString(
      <ExitWorkspaceView
        project={mockProject}
        onUpdateProject={() => {}}
      />
    );

    expect(html).toContain('Exit Disposition Milestones &amp; Task Assignments');
    expect(html).toContain('+ Invite via Email...');
    expect(html).toContain('data-testid="open-assign-modal-exit-task-1"');
  });

  it('renders AssignOrInviteModal in phase lead assignment mode with Radix Lyra styling', () => {
    const htmlRoster = renderToString(
      <AssignOrInviteModal
        isOpen={true}
        onClose={() => {}}
        projectId="deal-lifecycle"
        projectName="1247 Elm Street"
        assignType="phase"
        phaseKey="acquisition"
        phaseTitle="Acquisition"
        currentAssignee="Sarah Chen"
        existingMembers={mockProject.teamMembers}
        onAssignExisting={() => {}}
        onMemberInvitedAndAssigned={() => {}}
      />
    );

    expect(htmlRoster).toContain('Phase Lead Assignment');
    expect(htmlRoster).toContain('Assign Phase Lead');
    expect(htmlRoster).toContain('Phase: <strong class="text-white">Acquisition</strong>');
    expect(htmlRoster).toContain('Project Team (');
    expect(htmlRoster).toContain('+ Invite New Member via Email');
    expect(htmlRoster).toContain('Sarah Chen');
    expect(htmlRoster).toContain('Assigned');
    expect(htmlRoster).toContain('rounded-none');

    const htmlInvite = renderToString(
      <AssignOrInviteModal
        isOpen={true}
        onClose={() => {}}
        projectId="deal-lifecycle"
        projectName="1247 Elm Street"
        assignType="phase"
        phaseKey="acquisition"
        phaseTitle="Acquisition"
        initialTab="invite"
        existingMembers={mockProject.teamMembers}
        onAssignExisting={() => {}}
        onMemberInvitedAndAssigned={() => {}}
      />
    );

    expect(htmlInvite).toContain('Invite &amp; Assign Phase Lead');
    expect(htmlInvite).toContain('Acquisition Lead');
  });

  it('verifies SEED_PROJECTS has realistic sample phaseAssignees across lifecycle phases', () => {
    const project = SEED_PROJECTS.find((p) => p.id === 'deal-lifecycle');
    expect(project).toBeDefined();
    expect(project?.phaseAssignees).toBeDefined();
    expect(project?.phaseAssignees?.acquisition?.name).toBe('Sarah Chen');
    expect(project?.phaseAssignees?.purchase?.name).toBe('David Vance');
    expect(project?.phaseAssignees?.hold?.name).toBe('Elena Rostova');
    expect(project?.phaseAssignees?.exit?.name).toBe('Marcus Brody');
  });

  it('handles phase lead invitation and transactional email dispatch via SendGrid', async () => {
    process.env.TEST_AUTH_UID = 'test-investor-user';
    __clearSentEmailsForTesting();

    const request = new Request('http://localhost/api/invites', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: 'alex.rivera@apexcapital.com',
        name: 'Alex Rivera',
        role: 'Director of Underwriting',
        projectId: 'deal-lifecycle',
        assignType: 'phase',
        phaseKey: 'acquisition',
        phaseTitle: 'Acquisition',
      }),
    });

    const response = await handleInvitePost(request);
    expect(response.status).toBe(201);
    const data = (await response.json()) as any;
    expect(data.success).toBe(true);
    expect(data.assignType).toBe('phase');
    expect(data.phaseKey).toBe('acquisition');
    expect(data.member.name).toBe('Alex Rivera');

    // Seed project phaseAssignees updated
    const updated = getSeedProjectById('deal-lifecycle');
    expect(updated?.phaseAssignees?.acquisition?.name).toBe('Alex Rivera');
    expect(updated?.phaseAssignees?.acquisition?.email).toBe('alex.rivera@apexcapital.com');

    // Email dispatch recorded
    expect(sentEmailsForTesting.length).toBeGreaterThan(0);
    const lastEmail = sentEmailsForTesting[sentEmailsForTesting.length - 1];
    expect(lastEmail.subject).toContain('Project Invitation: Assigned to lead Acquisition on');
    expect(lastEmail.text).toContain('assigned to lead the Acquisition phase');
    expect(lastEmail.text).toContain('http://localhost/projects/deal-lifecycle?phase=acquisition');
  });

  it('handles step assignment invitation and transactional email dispatch via SendGrid', async () => {
    process.env.TEST_AUTH_UID = 'test-investor-user';
    __clearSentEmailsForTesting();

    const request = new Request('http://localhost/api/invites', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: 'jordan.contractor@builds.com',
        name: 'Jordan Contractor',
        role: 'General Contractor',
        projectId: 'deal-lifecycle',
        assignType: 'step',
        taskId: 'task-title-search',
        taskTitle: 'Preliminary Title Search',
      }),
    });

    const response = await handleInvitePost(request);
    expect(response.status).toBe(201);
    const data = (await response.json()) as any;
    expect(data.success).toBe(true);
    expect(data.assignType).toBe('step');
    expect(data.taskId).toBe('task-title-search');

    // Seed project tasks updated
    const updated = getSeedProjectById('deal-lifecycle');
    const task = updated?.tasks?.find((t) => t.id === 'task-title-search');
    expect(task?.assignedTo).toBe('Jordan Contractor');

    // Email dispatch recorded
    expect(sentEmailsForTesting.length).toBeGreaterThan(0);
    const lastEmail = sentEmailsForTesting[sentEmailsForTesting.length - 1];
    expect(lastEmail.subject).toContain('Project Invitation: Assigned to step "Preliminary Title Search"');
  });
});
