import React from 'react';
import fs from 'fs';
import path from 'path';
import { describe, expect, it, beforeEach } from '@jest/globals';
import { renderToString } from 'react-dom/server';
import ConversationalStepWizard from '../../components/projects/ConversationalStepWizard.js';
import AssignOrInviteModal from '../../components/projects/AssignOrInviteModal.js';
import ProjectDocumentsPanel, {
  REIL_CHECKLIST_MATRIX,
  formatBytes,
  resolveDocumentStatus,
  matchDocumentToRequirement,
} from '../../components/projects/ProjectDocumentsPanel.js';
import AcquisitionWorkspaceView from '../../components/projects/AcquisitionWorkspaceView.js';
import FundWorkspaceView from '../../components/projects/FundWorkspaceView.js';
import HoldWorkspaceView from '../../components/projects/HoldWorkspaceView.js';
import ExitWorkspaceView from '../../components/projects/ExitWorkspaceView.js';
import {
  ACQUISITION_CONVERSATIONAL_STEPS,
  FUND_CONVERSATIONAL_STEPS,
  HOLD_CONVERSATIONAL_STEPS,
  EXIT_CONVERSATIONAL_STEPS,
  getConversationalStepsForPhase,
  getConversationalStep,
} from '../../lib/projects/reil-conversational-steps.js';
import type { ProjectWorkspace, LegacyProjectPhase, ProjectDocument } from '../../lib/projects/types.js';
import { POST as handleInvitePost, GET as handleInviteGet } from '../../app/api/invites/route.js';
import { getSeedProjectById, updateSeedProject, SEED_PROJECTS } from '../../lib/projects/seed-data.js';
import { sentEmailsForTesting, __clearSentEmailsForTesting } from '../../lib/email/sendgrid-service.js';

const mockProjectFixture: ProjectWorkspace = {
  id: 'deal-lifecycle',
  project_id: 'deal-lifecycle',
  propertyName: '1247 Elm Street Apartments',
  address: '1247 Elm Street, Austin, TX 78702',
  property_address: '1247 Elm Street, Austin, TX 78702',
  city: 'Austin, TX',
  currentPhase: 'acquisition',
  phase: 'acquisition',
  status: 'Underwriting',
  dispositionType: 'SALE',
  purchasePrice: 485000,
  purchase_price: 485000,
  rehab_costs: 62000,
  exit_strategy: 'Fix & Flip',
  entity_type: 'LLC',
  phase_completion_pct: 35,
  estimatedIrr: 0.198,
  dealId: null,
  dealSlug: null,
  dealAddress: null,
  storage_used_bytes: 3450000,
  storageQuotaBytes: 536870912,
  todos: [],
  documents: [
    {
      doc_id: 'doc-prelim-flier',
      name: '1247_Elm_Street_OM_Flier.pdf',
      type: 'Preliminary Property Flier',
      url: '/documents/doc-prelim-flier',
      generated_at: '2026-04-01T10:00:00Z',
      phase: 'acquisition',
      status: 'verified',
      fileSize: '1.45 MB',
    },
    {
      doc_id: 'doc-underwriting-model',
      name: 'Underwriting_Pro_Forma_v2.xlsx',
      type: 'Underwriting Pro Forma',
      url: '/documents/doc-underwriting-model',
      generated_at: '2026-04-02T14:30:00Z',
      phase: 'acquisition',
      status: 'uploaded',
      fileSize: '820 KB',
    },
    {
      doc_id: 'doc-term-sheet',
      name: 'Executed_Senior_Term_Sheet.pdf',
      type: 'Executed Term Sheet',
      url: '/documents/doc-term-sheet',
      generated_at: '2026-04-10T09:15:00Z',
      phase: 'purchase',
      status: 'verified',
      fileSize: '2.10 MB',
    },
    {
      doc_id: 'doc-utility-confirmation',
      name: 'Austin_Energy_Transfer.pdf',
      type: 'Utility Transfer Confirmation',
      url: '/documents/doc-utility-confirmation',
      generated_at: '2026-04-15T11:00:00Z',
      phase: 'hold',
      status: 'uploaded',
      fileSize: '340 KB',
    },
    {
      doc_id: 'doc-exit-bov',
      name: 'Broker_Opinion_of_Value_CBRE.pdf',
      type: 'Broker Opinion of Value (BOV)',
      url: '/documents/doc-exit-bov',
      generated_at: '2026-04-20T16:00:00Z',
      phase: 'exit',
      status: 'verified',
      fileSize: '3.80 MB',
    },
  ],
  acquisitionStatus: 'under_contract',
  tasks: [
    {
      id: 'acq-step-1-lead',
      title: 'Lead Intake & Property Identification',
      status: 'complete',
      assignedTo: 'Sarah Chen',
      dueDate: '2026-04-15',
      isAutoGenerated: true,
    },
    {
      id: 'acq-step-2-underwriting',
      title: 'Financial Valuation & Deal Underwriting',
      status: 'pending',
      assignedTo: 'David Vance',
      dueDate: '2026-04-20',
      isAutoGenerated: true,
    },
    {
      id: 'fund-step-1-termsheet',
      title: 'Lender Term Sheet',
      status: 'complete',
      assignedTo: 'Lender / Debt Broker',
      dueDate: '2026-04-18',
      isAutoGenerated: true,
    },
    {
      id: 'hold-step-1-takeover',
      title: 'Property Takeover & Utilities',
      status: 'pending',
      assignedTo: 'Elena Rostova',
      dueDate: '2026-05-01',
      isAutoGenerated: true,
    },
    {
      id: 'exit-step-1-strategy',
      title: 'Strategy Determination & Valuation',
      status: 'pending',
      assignedTo: 'Marcus Brody',
      dueDate: '2026-06-01',
      isAutoGenerated: true,
    },
  ],
  teamMembers: [
    {
      id: 'team-acq-lead',
      uid: 'usr-acq-1',
      name: 'Sarah Chen',
      email: 'sarah.chen@apexcapital.com',
      role: 'Acquisitions Director',
      status: 'active',
    },
    {
      id: 'team-underwriter',
      uid: 'usr-und-2',
      name: 'David Vance',
      email: 'david.vance@apexcapital.com',
      role: 'Lead Underwriter',
      status: 'active',
    },
    {
      id: 'team-pm',
      uid: 'usr-pm-3',
      name: 'Elena Rostova',
      email: 'elena.rostova@buildprop.com',
      role: 'Property Manager',
      status: 'active',
    },
    {
      id: 'team-broker',
      uid: 'usr-brk-4',
      name: 'Marcus Brody',
      email: 'marcus.brody@compassre.com',
      role: 'Listing Broker',
      status: 'active',
    },
  ],
  phaseAssignees: {
    acquisition: {
      id: 'team-acq-lead',
      uid: 'usr-acq-1',
      name: 'Sarah Chen',
      email: 'sarah.chen@apexcapital.com',
      role: 'Acquisitions Director',
    },
    purchase: {
      id: 'team-underwriter',
      uid: 'usr-und-2',
      name: 'David Vance',
      email: 'david.vance@apexcapital.com',
      role: 'Senior Debt Lead',
    },
    hold: {
      id: 'team-pm',
      uid: 'usr-pm-3',
      name: 'Elena Rostova',
      email: 'elena.rostova@buildprop.com',
      role: 'Operations Director',
    },
    exit: {
      id: 'team-broker',
      uid: 'usr-brk-4',
      name: 'Marcus Brody',
      email: 'marcus.brody@compassre.com',
      role: 'Disposition Director',
    },
  },
  contingencies: [],
};

describe('Feature 4 Verification Suite: REIL Conversational Wizard, Team Assignment, and Anti-Slop Delivery Gate', () => {
  beforeEach(() => {
    process.env.TEST_AUTH_UID = 'test-investor-lead';
    __clearSentEmailsForTesting();
  });

  describe('1. End-to-End Conversational Step Wizard Across All 4 REIL Phases', () => {
    it('verifies Phase 1 Acquisition step wizard guided inquiry, legal rationale, and inputs', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      // Question Engine checks
      expect(html).toContain('data-testid="conversational-step-wizard"');
      expect(html).toContain('data-testid="conversational-step-question"');
      expect(html).toContain('Where is the property located, who is the seller, and what is the asking price?');

      // Legal & Financial Rationale
      expect(html).toContain('Why this matters (Legal &amp; Financial Rationale)');
      expect(html).toContain('Accurate property sourcing and seller identification establish the legal baseline');

      // Required Document Slot
      expect(html).toContain('data-testid="step-document-slot"');
      expect(html).toContain('Required Phase Documentation');
      expect(html).toContain('Property Flier or OM');
      expect(html).toContain('Preliminary Tax Record');
      expect(html).toContain('Zoning Classification Summary');

      // Input Form Fields
      expect(html).toContain('data-testid="step-response-form"');
      expect(html).toContain('Property Name / Label');
      expect(html).toContain('Property Address');
      expect(html).toContain('Seller Asking Price');

      // Step Navigation Pills & Metrics
      expect(html).toContain('Acquisition Lifecycle Milestones: Step 1 of 8');
      expect(html).toContain('data-testid="step-pill-1"');
      expect(html).toContain('data-testid="step-pill-8"');
      expect(html).toContain('data-testid="mark-step-complete-button"');
    });

    it('verifies Phase 2 Fund/Purchase step wizard inquiry, rationale, and input fields', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="purchase"
          phaseTitle="Fund"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('Fund Lifecycle Milestones: Step 1 of 6');
      expect(html).toContain('Which debt lender is providing senior financing, and what are the interest rate, LTV, and origination points?');
      expect(html).toContain('Comparing debt covenants, personal guarantee requirements, and prepayment penalties');
      expect(html).toContain('Senior Debt Lender Name');
      expect(html).toContain('Approved Facility Amount');
      expect(html).toContain('Interest Rate (%)');
      expect(html).toContain('Term Sheet');
    });

    it('verifies Phase 3 Hold step wizard inquiry, rationale, and input fields', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="hold"
          phaseTitle="Hold"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('Hold Lifecycle Milestones: Step 1 of 5');
      expect(html).toContain('Have keys and electronic lockboxes been transferred, security codes changed, and utilities placed in the operating entity name?');
      expect(html).toContain('Immediate takeover protocols safeguard asset security');
      expect(html).toContain('Official Takeover Date');
      expect(html).toContain('Electric Utility Account #');
      expect(html).toContain('Utility Transfer Receipts');
    });

    it('verifies Phase 4 Exit step wizard inquiry, rationale, and input fields', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="exit"
          phaseTitle="Exit"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('Exit Lifecycle Milestones: Step 1 of 4');
      expect(html).toContain('Which disposition path optimizes capital return: outright sale, cash-out refinance, condo sell-off, or 1031 exchange?');
      expect(html).toContain('Market cap rate cycles and prevailing mortgage interest rates dictate');
      expect(html).toContain('Selected Disposition Route');
      expect(html).toContain('Target Exit Valuation');
      expect(html).toContain('Comparative Market Analysis (CMA) / Broker Opinion of Value');
    });

    it('verifies step retrieval helper across all phases and step numbers', () => {
      const allPhases: LegacyProjectPhase[] = ['acquisition', 'purchase', 'hold', 'exit'];
      const counts: Record<LegacyProjectPhase, number> = {
        acquisition: 8,
        purchase: 6,
        hold: 5,
        exit: 4,
      };

      for (const phase of allPhases) {
        const steps = getConversationalStepsForPhase(phase);
        expect(steps.length).toBe(counts[phase]);
        for (let i = 1; i <= counts[phase]; i++) {
          const step = getConversationalStep(phase, i);
          expect(step).toBeDefined();
          expect(step?.stepNumber).toBe(i);
          expect(step?.conversationalQuestion.length).toBeGreaterThan(10);
          expect(step?.actionLabel.length).toBeGreaterThan(5);
        }
      }
    });
  });

  describe('2. Phase Lead Banner Rendering and Phase Assignment Trigger', () => {
    it('renders assigned phase lead with role badge and Change Phase Lead action button', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('data-testid="phase-leadership-banner"');
      expect(html).toContain('Phase Leadership');
      expect(html).toContain('Phase Lead:');
      expect(html).toContain('Sarah Chen');
      expect(html).toContain('Acquisitions Director');
      expect(html).toContain('data-testid="change-phase-lead-button"');
      expect(html).toContain('Change Phase Lead');
    });

    it('renders Unassigned state and invite lead trigger when phase assignee is absent', () => {
      const unassignedProject: ProjectWorkspace = {
        ...mockProjectFixture,
        phaseAssignees: {},
      };

      const html = renderToString(
        <ConversationalStepWizard
          project={unassignedProject}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={[]}
        />
      );

      expect(html).toContain('Phase Lead:');
      expect(html).toContain('Unassigned');
      expect(html).toContain('+ Assign / Invite Lead');
    });

    it('renders AssignOrInviteModal in phase lead assignment mode with project context', () => {
      const html = renderToString(
        <AssignOrInviteModal
          isOpen={true}
          onClose={() => {}}
          projectId="deal-lifecycle"
          projectName="1247 Elm Street Apartments"
          assignType="phase"
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          currentAssignee="Sarah Chen"
          existingMembers={mockProjectFixture.teamMembers}
          onAssignExisting={() => {}}
          onMemberInvitedAndAssigned={() => {}}
        />
      );

      expect(html).toContain('data-testid="assign-or-invite-modal"');
      expect(html).toContain('Phase Lead Assignment');
      expect(html).toContain('Assign Phase Lead');
      expect(html).toContain('Phase: <strong class="text-white">Acquisition</strong>');
      expect(html).toContain('data-testid="tab-existing-roster"');
      expect(html).toContain('Project Team');
      expect(html).toContain('data-testid="tab-invite-new"');
      expect(html).toContain('+ Invite New Member via Email');
    });
  });

  describe('3. Step Assignee Card Rendering and Step Assignment Modal Trigger', () => {
    it('renders embedded step assignee card with designated team member details and reassign trigger', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('data-testid="step-assignee-card"');
      expect(html).toContain('Step Assigned Lead');
      expect(html).toContain('Sarah Chen');
      expect(html).toContain('sarah.chen@apexcapital.com');
      expect(html).toContain('Recommended role:');
      expect(html).toContain('Acquisitions Director');
      expect(html).toContain('data-testid="assign-step-member-button"');
      expect(html).toContain('Reassign / Invite Member');
    });

    it('renders unassigned step state when task has no assigned team lead', () => {
      const projectWithoutStepAssignee: ProjectWorkspace = {
        ...mockProjectFixture,
        tasks: (mockProjectFixture.tasks || []).map((t) => ({ ...t, assignedTo: undefined, assigneeName: undefined })),
      };

      const html = renderToString(
        <ConversationalStepWizard
          project={projectWithoutStepAssignee}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('data-testid="step-assignee-card"');
      expect(html).toContain('Unassigned');
      expect(html).toContain('Assign or Invite Member');
    });

    it('renders AssignOrInviteModal in step assignment mode with specific task title', () => {
      const html = renderToString(
        <AssignOrInviteModal
          isOpen={true}
          onClose={() => {}}
          projectId="deal-lifecycle"
          projectName="1247 Elm Street Apartments"
          assignType="step"
          task={{
            id: 'acq-step-1-lead',
            title: 'Lead Intake & Property Identification',
            assignedTo: 'Sarah Chen',
            phase: 'acquisition',
          }}
          existingMembers={mockProjectFixture.teamMembers}
          onAssignExisting={() => {}}
          onMemberInvitedAndAssigned={() => {}}
        />
      );

      expect(html).toContain('Task Assignment');
      expect(html).toContain('Assign REIL Task');
      expect(html).toContain('Task: <strong class="text-white">Lead Intake &amp; Property Identification</strong>');
      expect(html).toContain('data-testid="member-row-Sarah Chen"');
      expect(html).toContain('Assigned');
      expect(html).toContain('data-testid="assign-button-David Vance"');
    });
  });

  describe('4. Dual-Mode Switcher Toggling Between Conversational Walkthrough and Executive Workspace', () => {
    it('renders mode toggle controls in wizard top bar with active status indication', () => {
      const html = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(html).toContain('data-testid="active-conversational-mode-button"');
      expect(html).toContain('Conversational Walkthrough');
      expect(html).toContain('data-testid="switch-executive-view-button"');
      expect(html).toContain('Executive Workspace →');
    });

    it('verifies all 4 phase workspaces support mode switcher toggles', () => {
      const acqHtml = renderToString(<AcquisitionWorkspaceView project={mockProjectFixture} onUpdateProject={() => {}} />);
      expect(acqHtml).toContain('data-testid="toggle-conversational-view"');
      expect(acqHtml).toContain('data-testid="toggle-executive-view"');

      const fundHtml = renderToString(<FundWorkspaceView project={mockProjectFixture} onUpdateProject={() => {}} />);
      expect(fundHtml).toContain('data-testid="toggle-conversational-view"');
      expect(fundHtml).toContain('data-testid="toggle-executive-view"');

      const holdHtml = renderToString(<HoldWorkspaceView project={mockProjectFixture} onUpdateProject={() => {}} />);
      expect(holdHtml).toContain('data-testid="toggle-conversational-view"');
      expect(holdHtml).toContain('data-testid="toggle-executive-view"');

      const exitHtml = renderToString(<ExitWorkspaceView project={mockProjectFixture} onUpdateProject={() => {}} />);
      expect(exitHtml).toContain('data-testid="toggle-conversational-view"');
      expect(exitHtml).toContain('data-testid="toggle-executive-view"');
    });
  });

  describe('5. Real API Route /api/invites Dispatch with SendGrid Transactional Mailer Payloads', () => {
    it('handles GET /api/invites returning active invites list and count', async () => {
      const getRes = await handleInviteGet();
      expect(getRes.status).toBe(200);
      const data = (await getRes.json()) as any;
      expect(Array.isArray(data.invites)).toBe(true);
      expect(typeof data.count).toBe('number');
    });

    it('rejects POST /api/invites missing valid email address with 400 Bad Request', async () => {
      const badReq = new Request('http://localhost/api/invites', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: 'Incomplete User' }),
      });
      const res = await handleInvitePost(badReq);
      expect(res.status).toBe(400);
      const err = (await res.json()) as any;
      expect(err.error).toContain('Valid email address is required');
    });

    it('processes Phase Lead invite and dispatches SendGrid transactional notification with phase link', async () => {
      const req = new Request('http://localhost/api/invites', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: 'caroline.capital@investments.com',
          name: 'Caroline Capital',
          role: 'Fund Management Lead',
          projectId: 'deal-lifecycle',
          assignType: 'phase',
          phaseKey: 'purchase',
          phaseTitle: 'Fund',
        }),
      });

      const response = await handleInvitePost(req);
      expect(response.status).toBe(201);
      const data = (await response.json()) as any;
      expect(data.success).toBe(true);
      expect(data.assignType).toBe('phase');
      expect(data.phaseKey).toBe('purchase');
      expect(data.member.name).toBe('Caroline Capital');
      expect(data.member.email).toBe('caroline.capital@investments.com');

      // Verify seed project persistence
      const updated = getSeedProjectById('deal-lifecycle');
      expect(updated?.phaseAssignees?.purchase?.name).toBe('Caroline Capital');

      // Verify SendGrid mailer payload
      expect(sentEmailsForTesting.length).toBeGreaterThan(0);
      const email = sentEmailsForTesting[sentEmailsForTesting.length - 1];
      const recipientEmail = Array.isArray(email.to) ? email.to[0]?.email : (email.to as any)?.email;
      expect(recipientEmail).toBe('caroline.capital@investments.com');
      expect(email.subject).toContain('Project Invitation: Assigned to lead Fund on');
      expect(email.text).toContain('assigned to lead the Fund phase');
      expect(email.text).toContain('https://paperworking.com/projects/deal-lifecycle?phase=purchase');
      expect(email.html).toContain('Phase Lead Assignment');
      expect(email.html).toContain('Caroline Capital');
    });

    it('processes Step Assignment invite and dispatches SendGrid transactional notification with step details', async () => {
      const req = new Request('http://localhost/api/invites', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: 'lucas.appraiser@valuations.com',
          name: 'Lucas Appraiser',
          role: 'Appraiser / Inspector',
          projectId: 'deal-lifecycle',
          assignType: 'step',
          taskId: 'acq-step-6-diligence',
          taskTitle: 'Due Diligence & Inspections',
        }),
      });

      const response = await handleInvitePost(req);
      expect(response.status).toBe(201);
      const data = (await response.json()) as any;
      expect(data.success).toBe(true);
      expect(data.assignType).toBe('step');
      expect(data.taskId).toBe('acq-step-6-diligence');

      // Verify seed project tasks persistence
      const updated = getSeedProjectById('deal-lifecycle');
      const diligenceTask = updated?.tasks?.find((t) => t.id === 'acq-step-6-diligence');
      expect(diligenceTask?.assignedTo).toBe('Lucas Appraiser');

      // Verify SendGrid mailer payload
      expect(sentEmailsForTesting.length).toBeGreaterThan(0);
      const email2 = sentEmailsForTesting[sentEmailsForTesting.length - 1];
      const recipientEmail2 = Array.isArray(email2.to) ? email2.to[0]?.email : (email2.to as any)?.email;
      expect(recipientEmail2).toBe('lucas.appraiser@valuations.com');
      expect(email2.subject).toContain('Project Invitation: Assigned to step "Due Diligence & Inspections"');
      expect(email2.text).toContain('Assigned Step: Due Diligence & Inspections');
      expect(email2.html).toContain('Team Step Assignment');
      expect(email2.html).toContain('Due Diligence & Inspections');
    });
  });

  describe('6. Document Vault 4-Phase Categorization, Requirements Matrix, and Status Badges', () => {
    it('verifies REIL requirements matrix contains exactly 25 statutory items across 4 phases', () => {
      expect(REIL_CHECKLIST_MATRIX).toHaveLength(25);

      const acqItems = REIL_CHECKLIST_MATRIX.filter((r) => r.phase === 'acquisition');
      const fundItems = REIL_CHECKLIST_MATRIX.filter((r) => r.phase === 'purchase');
      const holdItems = REIL_CHECKLIST_MATRIX.filter((r) => r.phase === 'hold');
      const exitItems = REIL_CHECKLIST_MATRIX.filter((r) => r.phase === 'exit');

      expect(acqItems).toHaveLength(8);
      expect(fundItems).toHaveLength(6);
      expect(holdItems).toHaveLength(6);
      expect(exitItems).toHaveLength(5);

      // Verify every requirement has complete metadata
      REIL_CHECKLIST_MATRIX.forEach((req) => {
        expect(req.id).toBeDefined();
        expect(req.title.length).toBeGreaterThan(3);
        expect(req.phaseNumber).toBeGreaterThanOrEqual(1);
        expect(req.phaseNumber).toBeLessThanOrEqual(4);
        expect(req.description.length).toBeGreaterThan(15);
        expect(req.aliases.length).toBeGreaterThan(0);
        expect(req.suggestedFileName.endsWith('.pdf')).toBe(true);
      });
    });

    it('verifies status resolver and document matching logic', () => {
      const docs: ProjectDocument[] = [
        {
          doc_id: 'doc-1',
          name: 'Signed_LOI_Accepted.pdf',
          type: 'Signed LOI',
          url: '/docs/1',
          generated_at: new Date().toISOString(),
          status: 'verified',
        },
        {
          doc_id: 'doc-2',
          name: 'Physical_Inspection_Report.pdf',
          type: 'Physical Inspection Report',
          url: '/docs/2',
          generated_at: new Date().toISOString(),
          status: 'uploaded',
        },
      ];

      const loiReq = REIL_CHECKLIST_MATRIX.find((r) => r.id === 'acq-loi')!;
      const inspectionReq = REIL_CHECKLIST_MATRIX.find((r) => r.id === 'acq-inspection')!;
      const missingReq = REIL_CHECKLIST_MATRIX.find((r) => r.id === 'acq-clear-to-close')!;

      const matchedLoi = matchDocumentToRequirement(loiReq, docs);
      expect(matchedLoi).toBeDefined();
      expect(resolveDocumentStatus(matchedLoi)).toBe('verified');

      const matchedInsp = matchDocumentToRequirement(inspectionReq, docs);
      expect(matchedInsp).toBeDefined();
      expect(resolveDocumentStatus(matchedInsp)).toBe('uploaded');

      const matchedMissing = matchDocumentToRequirement(missingReq, docs);
      expect(matchedMissing).toBeUndefined();
      expect(resolveDocumentStatus(matchedMissing)).toBe('required');
    });

    it('renders ProjectDocumentsPanel with 4-phase tabs, checklist stats, and workspace jump links', () => {
      const html = renderToString(<ProjectDocumentsPanel projectId="deal-lifecycle" />);

      expect(html).toContain('REIL Document Vault');
      expect(html).toContain('All Files');
      expect(html).toContain('1. Acquisition');
      expect(html).toContain('2. Fund');
      expect(html).toContain('3. Hold');
      expect(html).toContain('4. Exit');

      expect(html).toContain('Vault Storage Capacity');
      expect(html).toContain('REIL Checklist Compliance');
      expect(html).toContain('REIL Required Document Checklist Matrix');

      // Verify direct workspace phase route links
      expect(html).toContain('/projects/deal-lifecycle?phase=acquisition');
      expect(html).toContain('/projects/deal-lifecycle?phase=purchase');
      expect(html).toContain('/projects/deal-lifecycle?phase=hold');
      expect(html).toContain('/projects/deal-lifecycle?phase=exit');

      // Status badges
      expect(html).toContain('Required');
      expect(html).toContain('Upload Document');
    });
  });

  describe('7. Responsive Gospel Standards Compliance', () => {
    it('verifies all interactive elements enforce minimum 44px touch targets', () => {
      const wizardHtml = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      // Buttons, inputs, pills, switcher controls have min-h-[44px]
      expect(wizardHtml).toContain('min-h-[44px]');
      expect(wizardHtml).toContain('data-testid="change-phase-lead-button"');
      expect(wizardHtml).toContain('data-testid="assign-step-member-button"');
      expect(wizardHtml).toContain('data-testid="mark-step-complete-button"');

      const modalHtml = renderToString(
        <AssignOrInviteModal
          isOpen={true}
          onClose={() => {}}
          projectId="deal-lifecycle"
          projectName="1247 Elm Street Apartments"
          assignType="phase"
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          existingMembers={mockProjectFixture.teamMembers}
          onAssignExisting={() => {}}
          onMemberInvitedAndAssigned={() => {}}
        />
      );

      expect(modalHtml).toContain('min-h-[44px]');
      expect(modalHtml).toContain('data-testid="tab-existing-roster"');
      expect(modalHtml).toContain('data-testid="tab-invite-new"');

      const docsHtml = renderToString(<ProjectDocumentsPanel projectId="deal-lifecycle" />);
      expect(docsHtml).toContain('min-h-[44px]');
    });

    it('verifies input fields enforce text-base on mobile to eliminate iOS auto-zoom', () => {
      const wizardHtml = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      // Form inputs use text-base sm:text-xs
      expect(wizardHtml).toContain('text-base sm:text-xs');

      const modalHtml = renderToString(
        <AssignOrInviteModal
          isOpen={true}
          onClose={() => {}}
          projectId="deal-lifecycle"
          projectName="1247 Elm Street Apartments"
          assignType="phase"
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          initialTab="invite"
          existingMembers={mockProjectFixture.teamMembers}
          onAssignExisting={() => {}}
          onMemberInvitedAndAssigned={() => {}}
        />
      );

      expect(modalHtml).toContain('text-base sm:text-xs');
    });

    it('verifies container rule with fluid widths and no fixed-pixel overflows', () => {
      const docsHtml = renderToString(<ProjectDocumentsPanel projectId="deal-lifecycle" />);
      expect(docsHtml).toContain('max-w-[1200px]');
      expect(docsHtml).toContain('w-full');
      expect(docsHtml).not.toContain('w-[420px]');
      expect(docsHtml).not.toContain('w-[500px]');
      expect(docsHtml).not.toContain('w-[800px]');
    });
  });

  describe('8. Radix Lyra Design System & Anti-Slop Delivery Gate', () => {
    it('verifies strict Radix Lyra rounded-none controls and absence of pill buttons', () => {
      const wizardHtml = renderToString(
        <ConversationalStepWizard
          project={mockProjectFixture}
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          onUpdateProject={() => {}}
          onSwitchToExecutiveView={() => {}}
          activeRoster={mockProjectFixture.teamMembers}
        />
      );

      expect(wizardHtml).toContain('rounded-none');
      expect(wizardHtml).not.toContain('rounded-2xl');
      expect(wizardHtml).not.toContain('rounded-xl');
      expect(wizardHtml).not.toContain('rounded-full');

      const modalHtml = renderToString(
        <AssignOrInviteModal
          isOpen={true}
          onClose={() => {}}
          projectId="deal-lifecycle"
          projectName="1247 Elm Street Apartments"
          assignType="phase"
          phaseKey="acquisition"
          phaseTitle="Acquisition"
          existingMembers={mockProjectFixture.teamMembers}
          onAssignExisting={() => {}}
          onMemberInvitedAndAssigned={() => {}}
        />
      );

      expect(modalHtml).toContain('rounded-none');
      expect(modalHtml).not.toContain('rounded-2xl');
      expect(modalHtml).not.toContain('rounded-xl');
    });

    it('enforces strictly ZERO occurrences of forbidden term and ZERO em-dashes across all feature files', () => {
      const resolveFile = (subpath: string) => {
        const p1 = path.resolve(process.cwd(), subpath);
        if (fs.existsSync(p1)) return fs.readFileSync(p1, 'utf8');
        const p2 = path.resolve(process.cwd(), 'apps/web', subpath);
        if (fs.existsSync(p2)) return fs.readFileSync(p2, 'utf8');
        throw new Error(`File not found: ${subpath}`);
      };

      const filesToCheck = [
        'lib/projects/reil-conversational-steps.ts',
        'components/projects/ConversationalStepWizard.tsx',
        'components/projects/AssignOrInviteModal.tsx',
        'components/projects/ProjectDocumentsPanel.tsx',
        'app/api/invites/route.ts',
      ];

      const forbiddenWord = ['s', 'p', 'o', 'n', 's', 'o', 'r'].join('');
      const forbiddenPattern = new RegExp(forbiddenWord, 'i');
      const emDashChar = String.fromCharCode(8212);

      for (const filePath of filesToCheck) {
        const content = resolveFile(filePath);
        expect(content).not.toMatch(forbiddenPattern);
        expect(content.includes(emDashChar)).toBe(false);
      }
    });
  });
});
