'use client';

import React, { useState } from 'react';
import { useProjectStore } from '@/store/projectStore';
import { useAuth } from '@/context/AuthContext';
import { FileDown, FileSpreadsheet, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';

/* ═══════════════════════════════════════════════════════
   Statement Exporter — PDF & CSV Export Toolbar
   ─────────────────────────────────────────────────────
   Generates professional exports of P&L, Cash Flow,
   and Balance Sheet data. CPA-ready formatting.
   ═══════════════════════════════════════════════════════ */

type StatementType = 'pl' | 'cashflow' | 'balance';

export default function StatementExporter({ activeStatement }: { activeStatement: StatementType }) {
  const projects = useProjectStore(s => s.projects);
  const currentProject = useProjectStore(s => s.currentProject);
  const { user } = useAuth();
  const [generating, setGenerating] = useState<'pdf' | 'csv' | null>(null);

  const dateStr = new Date().toISOString().split('T')[0];

  const fetchExportData = async (format: 'pdf' | 'csv') => {
    if (!user) throw new Error('You must be signed in to export financial data.');

    const targetDeals = currentProject ? [currentProject] : projects;
    const projectIds = targetDeals.map(d => d.id).filter(Boolean);

    const idToken = await user.getIdToken();

    const response = await fetch('/api/reporting/export', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${idToken}`,
      },
      body: JSON.stringify({ format, type: activeStatement, projectIds }),
    });

    if (response.status === 401) throw new Error('Authentication required. Please sign in again.');
    if (response.status === 403) throw new Error('Access denied: you do not have permission to export this data.');
    if (!response.ok) throw new Error('Server returned an error while processing the export');

    return response;
  };

  // ─── PDF Generation ──────────────────────────────────
  const generatePdf = async () => {
    setGenerating('pdf');
    toast.loading('Generating PDF...', { id: 'stmt-pdf' });

    try {
      const response = await fetchExportData('pdf');
      const result = await response.json();
      
      if (!result.success) throw new Error(result.error);
      
      const data = result.data;

      const doc = new jsPDF();
      const title = activeStatement === 'pl' ? 'Profit & Loss Statement' :
                   activeStatement === 'cashflow' ? 'Cash Flow Statement' : 'Balance Sheet';

      // Header
      doc.setFontSize(20);
      doc.setTextColor(33, 33, 33);
      doc.text(title, 14, 20);
      doc.setFontSize(10);
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by PaperWorking · ${new Date().toLocaleDateString()}`, 14, 27);
      doc.setDrawColor(33, 33, 33);
      doc.setLineWidth(0.5);
      doc.line(14, 30, 196, 30);

      if (activeStatement === 'pl') {
        autoTable(doc, {
          startY: 35,
          head: [['Account', 'Amount']],
          body: data,
          theme: 'plain',
          styles: { fontSize: 10, cellPadding: 3 },
          headStyles: { fillColor: [245, 245, 245], textColor: [80, 80, 80], fontStyle: 'bold', fontSize: 8 },
          columnStyles: { 0: { cellWidth: 120 }, 1: { halign: 'right', fontStyle: 'normal' } },
          didParseCell: (hookData) => {
            const text = hookData.cell.raw as string;
            if (text && ['Revenue', 'Cost of Goods Sold', 'GROSS PROFIT', 'Operating Expenses', 'NET PROFIT / (LOSS)', 'Total Revenue', 'Total COGS', 'Total Operating Expenses'].includes(text)) {
              hookData.cell.styles.fontStyle = 'bold';
              if (text.includes('GROSS') || text.includes('NET')) {
                hookData.cell.styles.fillColor = [245, 245, 245];
              }
            }
          },
        });
      } else if (activeStatement === 'balance') {
        autoTable(doc, {
          startY: 35,
          head: [['Account', 'Amount']],
          body: data,
          theme: 'plain',
          styles: { fontSize: 10, cellPadding: 3 },
          headStyles: { fillColor: [245, 245, 245], textColor: [80, 80, 80], fontStyle: 'bold', fontSize: 8 },
          columnStyles: { 0: { cellWidth: 120 }, 1: { halign: 'right' } },
          didParseCell: (hookData) => {
            const text = hookData.cell.raw as string;
            if (text && ['ASSETS', 'LIABILITIES', "OWNER'S EQUITY", 'Total Assets', 'Total Liabilities'].includes(text)) {
              hookData.cell.styles.fontStyle = 'bold';
              hookData.cell.styles.fillColor = [245, 245, 245];
            }
          },
        });
      } else {
        autoTable(doc, {
          startY: 35,
          head: [data[0]],
          body: data.slice(1),
          theme: 'grid',
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [80, 80, 80], textColor: 255, fontSize: 8 },
          columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' } },
        });
      }

      const propName = currentProject?.propertyName?.replace(/\s+/g, '_') || 'Portfolio';
      const filename = `PaperWorking_${title.replace(/\s+/g, '_')}_${propName}_${dateStr}.pdf`;
      doc.save(filename);
      toast.success(`Downloaded: ${filename}`, { id: 'stmt-pdf', icon: '📊' });
    } catch (e) {
      console.error(e);
      toast.error('PDF generation failed. Check console.', { id: 'stmt-pdf' });
    } finally {
      setGenerating(null);
    }
  };

  // ─── CSV Generation ──────────────────────────────────
  const generateCsv = async () => {
    setGenerating('csv');
    toast.loading('Generating CSV...', { id: 'stmt-csv' });

    try {
      const response = await fetchExportData('csv');
      const csvString = await response.text();

      let title = '';
      if (activeStatement === 'pl') {
        title = 'Profit_Loss';
      } else if (activeStatement === 'balance') {
        title = 'Balance_Sheet';
      } else {
        title = 'Cash_Flow';
      }

      const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const propName = currentProject?.propertyName?.replace(/\s+/g, '_') || 'Portfolio';
      link.href = url;
      link.setAttribute('download', `PaperWorking_${title}_${propName}_${dateStr}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success(`CSV exported successfully!`, { id: 'stmt-csv', icon: '📋' });
    } catch (e) {
      console.error(e);
      toast.error('CSV export failed.', { id: 'stmt-csv' });
    } finally {
      setGenerating(null);
    }
  };

  const labels: Record<StatementType, string> = {
    pl: 'P&L Statement',
    cashflow: 'Cash Flow Statement',
    balance: 'Balance Sheet',
  };

  return (
    <div className="flex flex-wrap items-center justify-between gap-3 p-4 bg-bg-primary rounded-xl border border-border-accent">
      <div>
        <p className="text-sm font-semibold text-text-primary">Export: {labels[activeStatement]}</p>
        <p className="text-xs text-text-secondary">CPA-ready formatting with full line-item detail</p>
      </div>
      <div className="flex gap-2">
        <button
          onClick={generatePdf}
          disabled={generating !== null}
          className="flex items-center gap-1.5 bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-800 transition active:scale-95 disabled:opacity-50"
        >
          {generating === 'pdf' ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
          {generating === 'pdf' ? 'Generating...' : 'Download PDF'}
        </button>
        <button
          onClick={generateCsv}
          disabled={generating !== null}
          className="flex items-center gap-1.5 bg-bg-surface text-text-primary px-4 py-2 rounded-lg text-sm font-medium border border-border-accent hover:bg-bg-primary transition active:scale-95 disabled:opacity-50"
        >
          {generating === 'csv' ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileSpreadsheet className="w-4 h-4" />}
          {generating === 'csv' ? 'Exporting...' : 'Export CSV'}
        </button>
      </div>
    </div>
  );
}
