/**
 * Framework-independent application services extracted from Nest modules.
 */
export const SERVICES_PACKAGE_STATUS = 'phase-b18-admin-cutover' as const;

export {
  SESSION_COOKIE,
  ACCT_COOKIE,
  SUB_COOKIE,
  SESSION_ID_COOKIE,
  NEST_SESSION_MAX_AGE_MS,
  NEXT_SESSION_MAX_AGE_SEC,
  nestCookieBaseOptions,
  nextCookieBaseOptions,
  encodeNestSubCookie,
  encodeNextSubCookie,
  buildSessionCookieDescriptors,
  buildClearSessionCookieDescriptors,
  createIdentityProvisioningService,
  SessionCommandService,
  sessionCommandService,
  type CookieDescriptor,
  type SessionCookieOptions,
  type SubscriptionLookup,
  type IdentityUserRepository,
  type IdentityProvisioningService,
  type EstablishSessionInput,
  type EstablishSessionResult,
  type SessionCookiePolicyKind,
  type CreateIdentityProvisioningServiceInput,
} from './auth/index.js';

export {
  normalizeClientAccountType,
  isPlatformAdminUser,
  readCookieFromHeader,
  buildAuthUserFromPostgresUser,
  buildAuthUserForUid,
  createPrismaSessionUserStore,
  resolveAuthUserFromAccessToken,
  resolveAuthUserFromCredentials,
  type AuthUser,
  type PostgresUserProfile,
  type SessionUserStore,
  type SessionResolverDeps,
  type SessionCredentials,
} from './session/index.js';

export {
  ProjectsReadService,
  ProjectsReadValidationError,
  createProjectsReadService,
  ProjectsCommandService,
  ProjectsCommandValidationError,
  createProjectsCommandService,
  serializeProject,
  phaseNumberToName,
  type ProjectsReadRepository,
  type ProjectsReadServiceDeps,
  type ProjectsListResult,
  type ProjectGetResult,
  type SerializedProject,
  type ProjectCommandRecord,
  type ProjectCreateData,
  type ProjectsCommandRepository,
  type CreateProjectInput,
  type UpdateProjectInput,
  type ProjectCreateResult,
  type ProjectUpdateResult,
  type ProjectsCommandServiceDeps,
  ProjectKpiReadService,
  createProjectKpiReadService,
  buildProjectKpiEngineInputs,
  buildMockKpiTrends,
  auditProjectKpiInputProvenance,
  CANONICAL_KPI_DEFAULT_FIELDS,
  type ProjectKpiReadRepository,
  type ProjectKpiReadServiceDeps,
  type ProjectCurrentKpisResult,
  ProjectDocumentsReadService,
  createProjectDocumentsReadService,
  ProjectDocumentsCommandService,
  createProjectDocumentsCommandService,
  ProjectDocumentsValidationError,
  ProjectDocumentsStorageError,
  type ProjectDocumentsReadServiceDeps,
  type ProjectDocumentsCommandServiceDeps,
  type ProjectDocumentsListResult,
  type ProjectDocumentAccessResult,
  type UploadProjectDocumentResult,
} from './projects/index.js';

export type { FileStoragePort } from './storage/file-storage-port.js';

export {
  InboxReadService,
  createInboxReadService,
  InboxCommandService,
  createInboxCommandService,
  InboxItemNotFoundError,
  serializeInboxThread,
  type InboxReadRepository,
  type InboxReadServiceDeps,
  type InboxCommandRepository,
  type InboxCommandServiceDeps,
  type InboxPatchInput,
  type InboxUpdateResult,
  type InboxDeleteResult,
  type InboxItemRecord,
  type InboxThreadRecord,
  type InboxListResult,
} from './inbox/index.js';

export {
  PortfolioMetricsReadService,
  createPortfolioMetricsReadService,
  aggregatePortfolioMetricsFromProjects,
  type PortfolioMetricsReadRepository,
  type PortfolioMetricsReadServiceDeps,
  type PortfolioMetricsReadInput,
  type PortfolioMetricsProjectRow,
  type PortfolioMetricsResult,
  type PortfolioMetricsBlock,
  type PortfolioSummaryBlock,
} from './portfolio/index.js';

export {
  TeamMembersReadService,
  createTeamMembersReadService,
  TeamCommandService,
  createTeamCommandService,
  TeamInvalidRoleError,
  TeamMemberNotFoundError,
  TeamMemberIdRequiredError,
  TeamNoOrganizationError,
  type TeamMembersReadRepository,
  type TeamMembersReadServiceDeps,
  type TeamMembersReadInput,
  type TeamMembersListResult,
  type OrganizationMemberRecord,
  type TeamCommandRepository,
  type TeamCommandServiceDeps,
  type TeamOrgInput,
  type TeamInviteInput,
  type TeamCreateMemberInput,
  type TeamUpdateMemberInput,
  type OrganizationInviteRecord,
  type TeamInvitesListResult,
  type TeamInviteResult,
  type TeamCreateMemberResult,
  type TeamUpdateMemberResult,
  type TeamRemoveMemberResult,
} from './team/index.js';

export {
  MarketplaceProfileReadService,
  createMarketplaceProfileReadService,
  MarketplaceInvestorsReadService,
  createMarketplaceInvestorsReadService,
  serializeMarketplaceProfile,
  serializePublicInvestor,
  serializeInvestorProfileCard,
  type MarketplaceProfileReadRepository,
  type MarketplaceProfileReadServiceDeps,
  type MarketplaceProfileUserRow,
  type MarketplaceProfileRecord,
  type MarketplaceProfileResult,
  type MarketplaceInvestorsReadRepository,
  type MarketplaceInvestorsReadServiceDeps,
  type MarketplaceInvestorsListResult,
  type MarketplaceInvestorDetailResult,
  type MarketplaceListingsResult,
  type PublicInvestorRow,
  type MarketplaceListingRow,
  MarketplaceFollowCommandService,
  createMarketplaceFollowCommandService,
  MarketplaceFollowCommandValidationError,
  type MarketplaceFollowCommandRepository,
  type MarketplaceFollowCommandServiceDeps,
  type SetInvestorFollowInput,
  type InvestorFollowResult,
} from './marketplace/index.js';

export {
  DealsReadService,
  createDealsReadService,
  DealsCommandService,
  createDealsCommandService,
  DealsCommandValidationError,
  DealCommunicationValidationError,
  DealBroadcastService,
  createDealBroadcastService,
  DealReplyService,
  createDealReplyService,
  verifyBroadcastToken,
  signBroadcastToken,
  requireBroadcastTokenSecret,
  resolveBroadcastTokenSecret,
  resolveDealReplyWebhookSecret,
  resolveDealAppBaseUrl,
  buildDealExternalReplyUrl,
  DEFAULT_BROADCAST_TOKEN_TTL_SEC,
  type BroadcastTokenPayload,
  type DealsReadRepository,
  type DealsReadServiceDeps,
  type DealsListResult,
  type DealExistsResult,
  type DealRecord,
  type DealExistsPreview,
  type DealsCommandRepository,
  type DealsCommandServiceDeps,
  type CreateDealInput,
  type DealCreateResult,
  type DealBroadcastServiceDeps,
  type DealBroadcastInput,
  type DealBroadcastResult,
  type DealBroadcastRecipientLink,
  type DealReplyServiceDeps,
  type DealReplyInput,
  type DealReplyContext,
  type DealReplyResult,
  type DealReplyTrustMode,
  type DealCommunicationRepository,
} from './deals/index.js';

export {
  VendorsReadService,
  createVendorsReadService,
  VendorPortalReadService,
  createVendorPortalReadService,
  type VendorsReadRepository,
  type VendorsReadServiceDeps,
  type VendorsListResult,
  type VendorPortalReadRepository,
  type VendorPortalReadServiceDeps,
  type VendorPortalProfileResult,
  type VendorPortalRequestsResult,
  VendorPortalCommandService,
  createVendorPortalCommandService,
  VendorPortalCommandValidationError,
  type VendorPortalCommandRepository,
  type VendorPortalCommandServiceDeps,
  type VendorPortalProfileUpdateInput,
  type VendorPortalRequestUpdateInput,
  type VendorPortalProfileUpdateResult,
  type VendorPortalRequestUpdateResult,
} from './vendors/index.js';

export {
  PLAN_CATALOG,
  STARTING_PRICE,
  getCanonicalPlanName,
  listConfiguredStripePriceIds,
  resolvePlanId,
  resolveStripePriceId,
  validateAllowlistedPriceId,
  hasActiveEntitlement,
  hasVerifiedPaidSubscription,
  isFreePlan,
  BillingReadService,
  createBillingReadService,
  BillingCheckoutService,
  createBillingCheckoutService,
  BillingPortalService,
  createBillingPortalService,
  BillingSubscriptionCommandService,
  createBillingSubscriptionCommandService,
  StripeWebhookService,
  createStripeWebhookService,
  BillingValidationError,
  BillingForbiddenError,
  BillingNotFoundError,
  BillingUnavailableError,
  shouldUseMockBilling,
  stripeMockAllowed,
  resolveAllowedBillingRedirectUrl,
  type PlanId,
  type BillingInterval,
  type PlanConfig,
  type SubscriptionSnapshot,
  type BillingProviderPort,
  type BillingSubscriptionRepository,
  type SubscriptionRow,
  type BillingReadServiceDeps,
  type BillingSummaryResult,
  type BillingCheckoutInput,
  type BillingCheckoutResult,
  type BillingCheckoutServiceDeps,
  type BillingPortalInput,
  type BillingPortalResult,
  type BillingPortalServiceDeps,
  type BillingSubscriptionCommandInput,
  type BillingSubscriptionCommandServiceDeps,
  type StripeWebhookResult,
  type StripeWebhookServiceDeps,
} from './billing/index.js';

export {
  ReportsReadService,
  createReportsReadService,
  ReportsGenerateService,
  createReportsGenerateService,
  buildDemoPortfolioReport,
  buildLivePortfolioReport,
  ReportsGenerateValidationError,
  type ReportsReadRepository,
  type ReportProjectRow,
  type ReportsReadServiceDeps,
  type PortfolioReportResult,
  type PeriodReportResult,
  type ReportsGenerateServiceDeps,
  type ReportsGenerateInput,
  type GeneratedReportPayload,
  type ReportPdfExportPort,
  type BuildLivePortfolioReportDeps,
} from './reports/index.js';

export {
  ProfileReadService,
  createProfileReadService,
  ProfileCommandService,
  createProfileCommandService,
  ProfileForbiddenError,
  ProfileNotFoundError,
  ProfileValidationError,
  type ProfileSettingsRepository,
  type ProfileUserRow,
  type ProfileReadServiceDeps,
  type ProfileGetResult,
  type ProfileCommandServiceDeps,
  type ProfileUpdateInput,
  type ProfileUpdateResult,
  type SafeProfileDto,
  mapUserRowToSafeProfileDto,
  INTERNAL_PROFILE_RESPONSE_FIELDS,
} from './profile/index.js';

export {
  PortfolioInsightsReadService,
  createPortfolioInsightsReadService,
  type PortfolioInsightsReadRepository,
  type InsightsProjectRow,
  type PortfolioInsightsReadServiceDeps,
  type PortfolioInsightsResult,
} from './insights/index.js';

export {
  assertAdminUser,
  AdminOpsReadService,
  createAdminOpsReadService,
  AdminRentcastReadService,
  AdminLenderReadService,
  AdminAgentCrewReadService,
  AdminAgentCrewCommandService,
  createAdminRentcastReadService,
  createAdminLenderReadService,
  createAdminAgentCrewReadService,
  createAdminAgentCrewCommandService,
  type AdminReadRepository,
  type AdminOpsReadServiceDeps,
  type AdminRentcastReadServiceDeps,
  type AdminLenderReadServiceDeps,
  type AdminAgentCrewReadServiceDeps,
  type AdminAgentCrewCommandServiceDeps,
} from './admin/index.js';
