import {
  canTransitionAcquisitionStatus,
  validateAcquisitionTransition,
  executeAcquisitionTransition,
  IllegalStateTransitionError,
  DeadReasonRequiredError,
  MissingContractDataError,
  UnresolvedContingenciesError,
  ClosingDataRequiredError,
} from '../acquisition-state-machine.js';

describe('Requirement 2: Acquisition State Machine & Server-Side Enforcement', () => {
  const actorUid = 'user-acq-manager-1';

  describe('Legal Forward Transitions', () => {
    it('allows lead -> analyzing', () => {
      expect(canTransitionAcquisitionStatus('lead', 'analyzing')).toBe(true);
      const res = executeAcquisitionTransition('lead', 'analyzing', {}, actorUid);
      expect(res.updatedStatus).toBe('analyzing');
      expect(res.transitionLogEntry.from).toBe('lead');
      expect(res.transitionLogEntry.to).toBe('analyzing');
      expect(res.transitionLogEntry.actorUid).toBe(actorUid);
    });

    it('allows analyzing -> offer_sent', () => {
      expect(canTransitionAcquisitionStatus('analyzing', 'offer_sent')).toBe(true);
      const res = executeAcquisitionTransition('analyzing', 'offer_sent', {}, actorUid);
      expect(res.updatedStatus).toBe('offer_sent');
    });

    it('allows offer_sent -> negotiating', () => {
      expect(canTransitionAcquisitionStatus('offer_sent', 'negotiating')).toBe(true);
      const res = executeAcquisitionTransition('offer_sent', 'negotiating', {}, actorUid);
      expect(res.updatedStatus).toBe('negotiating');
    });

    it('allows offer_sent -> under_contract with executed PSA details', () => {
      expect(canTransitionAcquisitionStatus('offer_sent', 'under_contract')).toBe(true);
      const res = executeAcquisitionTransition(
        'offer_sent',
        'under_contract',
        {
          psaDocumentUrl: 'https://vault.paperworking.com/psa-signed.pdf',
          psaExecutionDate: '2026-09-10T10:00:00Z',
          emdAmount: 5000,
        },
        actorUid,
      );
      expect(res.updatedStatus).toBe('under_contract');
      expect(res.autoGeneratedTasks).toBeDefined();
      expect(res.autoGeneratedTasks).toHaveLength(11);
    });

    it('allows negotiating -> under_contract with executed PSA details', () => {
      expect(canTransitionAcquisitionStatus('negotiating', 'under_contract')).toBe(true);
      const res = executeAcquisitionTransition(
        'negotiating',
        'under_contract',
        {
          psaExecutionDate: '2026-09-10T10:00:00Z',
          emdAmount: 7500,
        },
        actorUid,
      );
      expect(res.updatedStatus).toBe('under_contract');
      expect(res.autoGeneratedTasks).toHaveLength(11);
    });

    it('allows under_contract -> due_diligence', () => {
      expect(canTransitionAcquisitionStatus('under_contract', 'due_diligence')).toBe(true);
      const res = executeAcquisitionTransition('under_contract', 'due_diligence', {}, actorUid);
      expect(res.updatedStatus).toBe('due_diligence');
    });

    it('allows due_diligence -> clear_to_close when contingencies satisfied', () => {
      expect(canTransitionAcquisitionStatus('due_diligence', 'clear_to_close')).toBe(true);
      const res = executeAcquisitionTransition(
        'due_diligence',
        'clear_to_close',
        {
          contingencies: [
            { type: 'inspection', status: 'satisfied' },
            { type: 'financing', status: 'waived' },
          ],
        },
        actorUid,
      );
      expect(res.updatedStatus).toBe('clear_to_close');
    });

    it('allows clear_to_close -> closed with closing date', () => {
      expect(canTransitionAcquisitionStatus('clear_to_close', 'closed')).toBe(true);
      const res = executeAcquisitionTransition(
        'clear_to_close',
        'closed',
        {
          closingDate: '2026-10-15T15:00:00Z',
          actualCashToClose: 185000,
        },
        actorUid,
      );
      expect(res.updatedStatus).toBe('closed');
    });

    it('allows reopening dead deal to analyzing with audit trail', () => {
      expect(canTransitionAcquisitionStatus('dead', 'analyzing')).toBe(true);
      const res = executeAcquisitionTransition(
        'dead',
        'analyzing',
        { note: 'Seller reopened negotiation with $30k price concession' },
        actorUid,
      );
      expect(res.updatedStatus).toBe('analyzing');
      expect(res.transitionLogEntry.note).toContain('$30k price concession');
    });
  });

  describe('Server-Side Rejection of Illegal Transitions (Typed Errors)', () => {
    it('throws IllegalStateTransitionError when skipping states: lead -> under_contract', () => {
      expect(canTransitionAcquisitionStatus('lead', 'under_contract')).toBe(false);
      expect(() =>
        executeAcquisitionTransition('lead', 'under_contract', {}, actorUid),
      ).toThrow(IllegalStateTransitionError);
    });

    it('throws IllegalStateTransitionError when skipping states: lead -> clear_to_close', () => {
      expect(canTransitionAcquisitionStatus('lead', 'clear_to_close')).toBe(false);
      expect(() =>
        executeAcquisitionTransition('lead', 'clear_to_close', {}, actorUid),
      ).toThrow(IllegalStateTransitionError);
    });

    it('throws IllegalStateTransitionError when skipping states: analyzing -> closed', () => {
      expect(canTransitionAcquisitionStatus('analyzing', 'closed')).toBe(false);
      expect(() =>
        executeAcquisitionTransition('analyzing', 'closed', {}, actorUid),
      ).toThrow(IllegalStateTransitionError);
    });

    it('throws IllegalStateTransitionError when transitioning backwards: closed -> analyzing', () => {
      expect(canTransitionAcquisitionStatus('closed', 'analyzing')).toBe(false);
      expect(() =>
        executeAcquisitionTransition('closed', 'analyzing', {}, actorUid),
      ).toThrow(IllegalStateTransitionError);
    });
  });

  describe('Entry & Exit Guard Enforcement', () => {
    it('throws DeadReasonRequiredError when archiving without a dead reason category', () => {
      expect(() =>
        executeAcquisitionTransition('analyzing', 'dead', {}, actorUid),
      ).toThrow(DeadReasonRequiredError);
    });

    it('throws DeadReasonRequiredError when notes are too short', () => {
      expect(() =>
        executeAcquisitionTransition(
          'offer_sent',
          'dead',
          { deadReason: 'offer_rejected', deadReasonNotes: 'no' },
          actorUid,
        ),
      ).toThrow(DeadReasonRequiredError);
    });

    it('records structured deadRecord when archiving with valid category and notes', () => {
      const res = executeAcquisitionTransition(
        'negotiating',
        'dead',
        {
          deadReason: 'numbers_failed',
          deadReasonNotes: 'Seller counter at $540k falls below minimum 5.5% cap rate',
        },
        actorUid,
      );
      expect(res.updatedStatus).toBe('dead');
      expect(res.deadRecord).toBeDefined();
      expect(res.deadRecord?.deadReasonCategory).toBe('numbers_failed');
      expect(res.deadRecord?.previousStatus).toBe('negotiating');
      expect(res.deadRecord?.archivedByUid).toBe(actorUid);
    });

    it('throws MissingContractDataError when entering under_contract without PSA details', () => {
      expect(() =>
        executeAcquisitionTransition('offer_sent', 'under_contract', {}, actorUid),
      ).toThrow(MissingContractDataError);
    });

    it('throws UnresolvedContingenciesError when entering clear_to_close with open contingencies', () => {
      expect(() =>
        executeAcquisitionTransition(
          'due_diligence',
          'clear_to_close',
          {
            contingencies: [
              { type: 'inspection', status: 'satisfied' },
              { type: 'financing', status: 'open' },
            ],
          },
          actorUid,
        ),
      ).toThrow(UnresolvedContingenciesError);
    });

    it('throws ClosingDataRequiredError when entering closed without closing date', () => {
      expect(() =>
        executeAcquisitionTransition('clear_to_close', 'closed', {}, actorUid),
      ).toThrow(ClosingDataRequiredError);
    });
  });
});
